faq_data = {
    "medico": {
        "nombre": "Médico General",
        "descripcion": "Consultas clínicas, atención primaria y orientación general de salud.",
        "faqs": [
            ("¿Atienden con obra social?", "Sí, trabajamos con las principales obras sociales del país."),
            ("¿Atienden sin turno?", "Recomendamos sacar turno, pero también atendemos urgencias."),
            ("¿Realizan controles de rutina?", "Sí, hacemos chequeos generales, clínicos y derivaciones si es necesario."),
            ("¿Atienden urgencias?", "Sí, contamos con atención médica inmediata ante emergencias."),
            ("¿Hacen certificados médicos?", "Sí, realizamos certificados de salud, escolares y laborales."),
            ("¿Cuánto cuesta una consulta?", "La consulta tiene un valor de referencia, pero puede variar según cobertura."),
            ("¿Atienden a domicilio?", "Sí, ofrecemos atención médica domiciliaria según disponibilidad."),
            ("¿Recetan medicamentos?", "Sí, prescribimos tratamientos médicos tras la consulta."),
            ("¿Puedo pagar con tarjeta?", "Aceptamos efectivo, débito, crédito y transferencias."),
            ("¿Tienen horarios extendidos?", "Sí, atendemos de lunes a viernes hasta las 20 hs y sábados por la mañana."),
            ("¿Puedo pedir turno online?", "Sí, podés reservar desde nuestra web o por WhatsApp."),
            ("¿Realizan electrocardiogramas?", "Sí, contamos con equipamiento para ECG en el consultorio."),
            ("¿Pueden derivar a especialistas?", "Sí, hacemos derivaciones según diagnóstico médico inicial."),
            ("¿Tienen historia clínica digital?", "Sí, registramos todos los antecedentes y consultas en sistema."),
            ("¿Atención con prepaga?", "Sí, trabajamos con prepagas líderes del país."),
        ]
    },

    "cirujano": {
        "nombre": "Cirujano",
        "descripcion": "Consultas prequirúrgicas, intervenciones y seguimiento post-operatorio.",
        "padre": "medico",
        "faqs": [
            ("¿Qué tipo de cirugías realizan?", "Cirugías generales, laparoscópicas y procedimientos ambulatorios."),
            ("¿Cómo es la preparación prequirúrgica?", "Se requiere análisis previos y consulta con el anestesista."),
            ("¿Trabajan con clínicas u hospitales privados?", "Sí, realizamos intervenciones en varias instituciones asociadas."),
            ("¿La consulta incluye diagnóstico por imágenes?", "Evaluamos estudios previos y solicitamos nuevos si es necesario."),
            ("¿Hacen cirugías con láser?", "Sí, dependiendo del procedimiento y el diagnóstico previo."),
            ("¿Atienden post-operatorios?", "Sí, realizamos seguimiento y curaciones después de la cirugía."),
            ("¿Atienden con obra social?", "Sí, operamos con cobertura de varias obras sociales."),
            ("¿Cuál es el tiempo de recuperación habitual?", "Depende del procedimiento, pero suele requerir 7 a 14 días de reposo."),
            ("¿Puedo financiar la cirugía?", "Sí, tenemos planes de pago con tarjeta y convenios con clínicas."),
            ("¿Cuánto cuesta una intervención?", "El presupuesto se define tras la consulta inicial y estudios previos."),
            ("¿Realizan cirugías ambulatorias?", "Sí, muchos procedimientos no requieren internación prolongada."),
            ("¿Hacen extracciones de lunares o quistes?", "Sí, procedimientos menores se realizan en consultorio."),
            ("¿Trabajan con anestesistas certificados?", "Sí, nuestro equipo incluye profesionales acreditados."),
            ("¿Atienden niños?", "Sí, tenemos experiencia en cirugía pediátrica también."),
            ("¿Puedo pedir segunda opinión?", "Claro, revisamos estudios y damos opinión médica profesional."),
        ]
    },

    "oftalmologo": {
        "nombre": "Oftalmólogo",
        "descripcion": "Diagnóstico y tratamiento de problemas de visión, exámenes visuales y lentes.",
        "padre": "medico",
        "faqs": [
            ("¿Hacen exámenes visuales completos?", "Sí, revisamos agudeza visual, presión ocular y fondo de ojo."),
            ("¿Pueden recetar anteojos?", "Claro, emitimos recetas ópticas válidas para todas las ópticas."),
            ("¿Atienden niños y adultos?", "Sí, realizamos controles oftalmológicos en todas las edades."),
            ("¿Atienden por obra social?", "Sí, trabajamos con obras sociales y prepagas reconocidas."),
            ("¿Atienden emergencias visuales?", "Sí, en caso de visión borrosa repentina, accidentes o infecciones."),
            ("¿Hacen cirugía de cataratas?", "Sí, realizamos diagnósticos y derivaciones quirúrgicas para cataratas."),
            ("¿Controlan la presión ocular?", "Sí, hacemos pruebas de tonometría para prevenir glaucoma."),
            ("¿Venden lentes de contacto?", "No vendemos, pero hacemos recetas y adaptaciones para lentes."),
            ("¿Atienden a adultos mayores?", "Sí, con enfoque especial en enfermedades como degeneración macular."),
            ("¿Cuánto cuesta una consulta oftalmológica?", "Consultá nuestros valores o accedé con tu cobertura médica."),
            ("¿Controlan la vista para licencias?", "Sí, hacemos informes para carnet de conducir y otras licencias."),
            ("¿Puedo hacerme controles anuales?", "Sí, es recomendable un chequeo visual por año."),
            ("¿Revisan fondo de ojo?", "Sí, es parte de los exámenes completos que realizamos."),
            ("¿Atienden pacientes con diabetes?", "Sí, controlamos retinopatía diabética y otras complicaciones visuales."),
            ("¿Puedo traer estudios previos?", "Sí, ayudan a evaluar mejor la evolución de tu salud visual."),
        ]
    },

        "dentista": {
        "nombre": "Dentista",
        "descripcion": "Odontología general, estética, cirugías y prevención bucal.",
        "padre": "medico",
        "faqs": [
            ("¿Atienden con obra social?", "Sí, trabajamos con varias obras sociales y prepagas del país."),
            ("¿Realizan limpiezas dentales?", "Sí, recomendamos una limpieza profesional cada 6 meses."),
            ("¿Colocan implantes?", "Sí, realizamos implantes dentales con materiales de alta calidad."),
            ("¿Atienden urgencias dentales?", "Sí, para casos como dolor intenso, infecciones o piezas fracturadas."),
            ("¿Hacen ortodoncia?", "Sí, colocamos brackets tradicionales y alineadores invisibles."),
            ("¿Realizan tratamientos de conducto?", "Sí, contamos con especialistas en endodoncia."),
            ("¿Atienden niños?", "Sí, ofrecemos odontopediatría en un entorno amigable."),
            ("¿Hacen blanqueamiento dental?", "Sí, con técnicas seguras y resultados visibles desde la primera sesión."),
            ("¿Cuánto cuesta una consulta?", "Depende del tratamiento, pero ofrecemos primera evaluación sin cargo."),
            ("¿Puedo pagar en cuotas?", "Sí, aceptamos pagos con tarjeta y financiación según el tratamiento."),
            ("¿Hacen prótesis dentales?", "Sí, removibles, fijas y sobre implantes."),
            ("¿Tienen guardias los fines de semana?", "Sí, con agenda previa para urgencias odontológicas."),
            ("¿Atienden pacientes con ansiedad o miedo?", "Sí, tenemos experiencia en sedación consciente y trato personalizado."),
            ("¿Puedo pedir un presupuesto por WhatsApp?", "Sí, enviando fotos o estudios previos te damos una orientación."),
            ("¿Hacen extracciones dentales?", "Sí, realizamos extracciones simples y complejas en consultorio."),
        ]
    },
    
    "kinesiologo": {
        "nombre": "Kinesiólogo",
        "descripcion": "Rehabilitación física, recuperación de lesiones y tratamientos funcionales.",
        "padre": "medico",
        "faqs": [
            ("¿Qué tipo de tratamientos realizan?", "Rehabilitación post-quirúrgica, lesiones deportivas, dolores articulares y tratamientos preventivos."),
            ("¿Atienden con derivación médica?", "Sí, trabajamos con derivaciones de médicos clínicos, traumatólogos o reumatólogos."),
            ("¿Atienden con obra social?", "Sí, trabajamos con la mayoría de las obras sociales y prepagas."),
            ("¿Es necesario sacar turno?", "Sí, recomendamos agendar turno previamente para una atención personalizada."),
            ("¿Cuánto dura cada sesión?", "Las sesiones duran entre 30 y 45 minutos, según la patología y el tratamiento."),
            ("¿Atienden a domicilio?", "Sí, ofrecemos servicio domiciliario en casos especiales o con movilidad reducida."),
            ("¿Qué aparatología utilizan?", "Contamos con electroestimulación, ultrasonido, magnetoterapia y láser, entre otros."),
            ("¿Atienden adultos mayores?", "Sí, adaptamos los tratamientos a la movilidad y necesidades del paciente."),
            ("¿Realizan ejercicios personalizados?", "Sí, cada plan se adapta al diagnóstico funcional del paciente."),
            ("¿Tratan escoliosis o problemas posturales?", "Sí, diseñamos rutinas de fortalecimiento y corrección postural."),
            ("¿Puedo hacer sesiones preventivas sin dolor?", "Sí, muchas personas realizan kinesiología preventiva para evitar lesiones."),
            ("¿Hacen drenaje linfático?", "Sí, realizamos técnicas manuales y mecánicas de drenaje linfático."),
            ("¿Atención para deportistas?", "Sí, tratamos esguinces, desgarros, tendinitis y preparamos planes de readaptación deportiva."),
            ("¿Cuánto cuesta una sesión particular?", "Varía según el tratamiento, pero ofrecemos presupuestos accesibles."),
            ("¿Brindan informes para seguros o ART?", "Sí, entregamos informes profesionales a pedido del paciente o cobertura."),
        ]
    },
    "heladeria": {
        "nombre": "Heladería",
        "descripcion": "Venta de helado artesanal, delivery, sabores y atención al cliente.",
        "faqs": [
            ("¿Qué sabores tienen disponibles?", "Contamos con más de 30 sabores entre clásicos y especiales. Consultá nuestra carta actualizada en redes o WhatsApp."),
            ("¿Tienen sabores sin azúcar?", "Sí, ofrecemos opciones sin azúcar aptas para diabéticos."),
            ("¿Venden helado por kilo?", "Sí, podés comprar en 1/4 kg, 1/2 kg y 1 kg. También vendemos potes familiares."),
            ("¿Ofrecen envíos a domicilio?", "Sí, realizamos delivery en la ciudad. Podés pedir por WhatsApp o por apps."),
            ("¿Cuál es el mínimo para envío?", "El pedido mínimo para delivery es de 1/4 kg."),
            ("¿Cuáles son los métodos de pago?", "Aceptamos efectivo, tarjetas y transferencias. También pago online."),
            ("¿Tienen helado sin lactosa?", "Sí, ofrecemos opciones sin lactosa y veganas."),
            ("¿Hay promociones o combos?", "Sí, tenemos promos semanales y combos especiales. ¡Consultanos!"),
            ("¿Se pueden combinar sabores?", "Sí, podés elegir hasta 3 sabores por kilo."),
            ("¿Atienden todos los días?", "Sí, abrimos todos los días de 12 a 00 hs, incluidos feriados."),
            ("¿Tienen local para consumir en el lugar?", "Sí, tenemos mesas en el salón y en la vereda."),
            ("¿Puedo encargar tortas heladas?", "Sí, hacemos tortas heladas personalizadas con pedido anticipado."),
            ("¿Tienen sabores para niños?", "Sí, contamos con opciones dulces y divertidas para los más chicos."),
            ("¿Hacen envíos por apps como PedidosYa o Rappi?", "Sí, estamos disponibles en las principales apps de delivery."),
            ("¿Dónde puedo ver el menú completo?", "En nuestras redes sociales o pidiéndolo por mensaje directo."),
        ]
    },
    "bodega": {
        "nombre": "Bodega",
        "descripcion": "Venta de vinos, enoturismo, degustaciones y atención a clientes mayoristas y minoristas.",
        "faqs": [
            ("¿Qué tipos de vinos ofrecen?", "Ofrecemos vinos tintos, blancos, rosados y espumantes."),
            ("¿Tienen tienda online?", "Sí, podés comprar desde nuestra tienda virtual con envíos a todo el país."),
            ("¿Hacen envíos a domicilio?", "Sí, enviamos a todo el país y también al exterior bajo pedido especial."),
            ("¿Puedo visitar la bodega?", "Sí, organizamos visitas guiadas con degustación previa reserva."),
            ("¿Ofrecen degustaciones?", "Sí, tenemos degustaciones programadas y también privadas para grupos."),
            ("¿Tienen vinos premiados?", "Sí, varios de nuestros vinos han sido reconocidos en concursos internacionales."),
            ("¿Hacen envíos al exterior?", "Sí, realizamos exportaciones y envíos particulares con autorización previa."),
            ("¿Se puede pagar online?", "Sí, aceptamos pagos con tarjeta, transferencia y plataformas digitales."),
            ("¿Venden vinos por caja?", "Sí, ofrecemos descuentos por compra en caja cerrada."),
            ("¿Tienen atención a mayoristas?", "Sí, contamos con precios y atención exclusiva para distribuidores."),
            ("¿Puedo reservar eventos en la bodega?", "Sí, alquilamos espacios para eventos corporativos y sociales."),
            ("¿Tienen club de vinos?", "Sí, tenemos un club con envíos mensuales y beneficios exclusivos."),
            ("¿Cuál es el vino más vendido?", "Nuestro Malbec Reserva es el favorito por su excelente relación calidad-precio."),
            ("¿Puedo hacer un regalo personalizado?", "Sí, armamos cajas de regalo y etiquetado personalizado para empresas o particulares."),
            ("¿Tienen vinos orgánicos o biodinámicos?", "Sí, ofrecemos líneas certificadas que respetan procesos naturales."),
        ]
    },
}



