# Contenido para tu archivo faq_questions.py MODIFICADO

faq_data = {
    "medico": {
        "nombre": "Médico General",
        "descripcion": "Consultas clínicas, atención primaria y orientación general de salud.",
        "categorias": {
            "General": [
                ["¿Atienden con obra social?", "Sí, trabajamos con las principales obras sociales del país. Para confirmar si aceptamos la tuya, por favor contáctanos al [telefono] o visita [linkWeb]."],
                ["¿Atienden sin turno?", "Recomendamos sacar turno para una mejor atención, pero también atendemos urgencias según disponibilidad. Llámanos al [telefono] en caso de urgencia."],
                ["¿Realizan controles de rutina?", "Sí, en [nombreEmpresa] hacemos chequeos generales y clínicos. Podemos realizar derivaciones a especialistas si es necesario."],
                ["¿Atienden urgencias?", "Sí, contamos con atención médica para ciertas urgencias. Te recomendamos llamar previamente al [telefono] para coordinar."],
                ["¿Hacen certificados médicos?", "Sí, realizamos certificados de salud, escolares y laborales tras la correspondiente evaluación médica."],
                ["¿Cuánto cuesta una consulta?", "El costo de la consulta puede variar según tu cobertura médica o la complejidad. Para información de precios, por favor contáctanos al [telefono]."],
                ["¿Atienden a domicilio?", "Sí, ofrecemos atención médica domiciliaria en algunos casos especiales. Consulta al [telefono] por disponibilidad y zonas de cobertura."],
                ["¿Recetan medicamentos?", "Sí, como parte del tratamiento, nuestros profesionales prescriben medicamentos luego de la evaluación en consulta."],
                ["¿Puedo pagar con tarjeta?", "Sí, en [nombreEmpresa] aceptamos tarjeta de débito, crédito, transferencias y las principales billeteras virtuales."],
                ["¿Tienen horarios extendidos?", "Sí, nuestro horario de atención es [horario]. Los sábados atendemos por la mañana."],
                ["¿Puedo pedir turno online?", "Sí, podés reservar turno desde nuestro sitio web [linkWeb] o contactándonos por WhatsApp al [telefono]."],
                ["¿Realizan electrocardiogramas?", "Sí, contamos con equipamiento para realizar electrocardiogramas (ECG) y otros estudios básicos en nuestro consultorio."],
                ["¿Pueden derivar a especialistas?", "Sí, luego de una evaluación inicial, realizamos las derivaciones pertinentes a otros especialistas si tu caso lo requiere."],
                ["¿Tienen historia clínica digital?", "Sí, en [nombreEmpresa] registramos todas las consultas en una plataforma digital segura para un mejor seguimiento de tu salud."],
                ["¿Atención con prepaga?", "Sí, trabajamos con varias prepagas líderes del país. Para confirmar la tuya, contáctanos al [telefono]."],
                ["¿Atienden niños y adultos?", "Sí, en [nombreEmpresa] realizamos atención clínica para pacientes de todas las edades."],
                ["¿Toman presión y controlan glucosa?", "Sí, como parte de la consulta realizamos controles básicos como toma de presión arterial, control de glucemia y saturación de oxígeno."],
                ["¿Vacunan en el consultorio?", "Aplicamos algunas vacunas del calendario y otras recomendadas, según disponibilidad. Consulta al [telefono] por la vacuna que necesitas."],
                ["¿Hacen certificados para actividades físicas?", "Sí, realizamos la evaluación médica y emitimos certificados de aptitud física."],
                ["¿Tienen servicio de nutricionista?", "Sí, contamos con profesionales especializados en nutrición y dietética para asesorarte."],
                ["¿Atienden los fines de semana?", "Atendemos los sábados por la mañana ([horario]). Para domingos o feriados, por favor consulta disponibilidad llamando al [telefono]."],
                ["¿Ofrecen seguimiento de enfermedades crónicas?", "Sí, realizamos controles periódicos y seguimiento para pacientes con condiciones como hipertensión, diabetes, entre otras."],
                ["¿Atienden por videollamada?", "Sí, ofrecemos la opción de consultas virtuales para ciertos casos y seguimientos. Puedes agendarla a través de [linkWeb] o llamando al [telefono]."],
                ["¿Se puede cambiar o cancelar un turno?", "Sí, podés reprogramar o cancelar tu turno contactándonos al [telefono] con al menos 12-24 horas de anticipación, según nuestras políticas detalladas en [linkWeb]."],
                ["¿Qué documentación debo llevar a la consulta?", "Por favor trae tu DNI y, si tienes, la credencial de tu obra social o prepaga. Si es una consulta de seguimiento, trae también tus estudios previos relevantes."],
                ["¿Realizan análisis clínicos?", "Trabajamos con laboratorios asociados de confianza. Podemos indicarte dónde realizarte extracciones y cómo recibir tus resultados, a menudo por email o portal online."],
                ["¿Hacen estudios ginecológicos o PAP?", "Sí, contamos con profesionales que realizan controles ginecológicos, PAP y colposcopías. Puedes solicitar turno al [telefono]."],
                ["¿Tienen atención pediátrica?", "Sí, ofrecemos atención clínica para niños desde los primeros meses de vida. Agenda una consulta al [telefono]."],
                ["¿Puedo consultar por dolor de cabeza o malestar general?", "Sí, por supuesto. Evaluamos síntomas comunes como esos y te orientamos sobre el tratamiento adecuado o si necesitas estudios adicionales."],
                ["¿Atienden a personas mayores?", "Sí, tenemos experiencia en atención geriátrica y ofrecemos un cuidado integral adaptado a las necesidades de los adultos mayores."]
            ]
        }
    },
    "bodega": {
        "nombre": "Bodega",
        "descripcion": "Venta de vinos, enoturismo, degustaciones y atención a clientes mayoristas y minoristas.",
        "categorias": {
            "Ventas y envíos": [
                ["¿Qué tipos de vinos ofrecen?", "En [nombreEmpresa] ofrecemos una selecta variedad de vinos, incluyendo tintos, blancos, rosados y espumantes. Visita [linkWeb] para ver nuestro catálogo completo."],
                ["¿Tienen tienda online?", "Sí, podés comprar todos nuestros productos en nuestra tienda virtual [linkWeb], disponible las 24 hs, con envíos a todo el país."],
                ["¿Hacen envíos a domicilio?", "Sí, realizamos envíos a domicilio en todo el país. Para envíos internacionales, por favor contáctanos al [telefono] o vía email."],
                ["¿Venden vinos por caja?", "Sí, ofrecemos descuentos especiales por la compra de vinos por caja cerrada. Consulta las opciones en [linkWeb] o preguntanos."],
                ["¿Qué medios de pago aceptan?", "Aceptamos tarjetas de débito, crédito, transferencia bancaria y MercadoPago. Puedes ver todas las opciones en [linkWeb] al finalizar tu compra."],
                ["¿Tienen promociones vigentes?", "Sí, constantemente tenemos promociones y combos especiales. Te invitamos a ver las ofertas actuales en nuestro sitio web [linkWeb] o suscribirte a nuestro newsletter."],
                ["¿Ofrecen envíos gratis?", "Sí, generalmente ofrecemos envíos gratuitos para compras que superan un monto determinado. Consulta las condiciones actuales en [linkWeb]."],
                ["¿Hacen envíos en el día?", "Para algunas zonas cercanas a nuestra bodega en [ubicacion], ofrecemos envíos en el día según horario de compra. Consulta al [telefono]."],
                ["¿Cuánto demora el envío?", "La demora estimada es de 2 a 7 días hábiles, dependiendo del destino. En zonas urbanas principales suele ser más rápido."],
                ["¿Puedo programar el envío para una fecha específica?", "Sí, al realizar tu compra online en [linkWeb], usualmente puedes indicar una fecha de entrega preferida o dejar una nota para coordinar."],
                ["¿Puedo hacer un regalo a domicilio?", "¡Por supuesto! Ofrecemos opciones de empaque para regalo y la posibilidad de incluir una dedicatoria. Puedes gestionarlo al comprar en [linkWeb]."],
                ["¿Se pueden personalizar las etiquetas?", "Sí, para pedidos especiales como eventos o regalos corporativos, ofrecemos servicio de etiquetas personalizadas. Contáctanos al [telefono] para más detalles."],
                ["¿Qué pasa si no hay nadie para recibir el pedido?", "La empresa de logística intentará una segunda entrega o dejará una notificación. Generalmente reprogramamos el envío; consulta nuestras políticas en [linkWeb]."],
                ["¿Qué empresas de envío utilizan?", "Trabajamos con reconocidos operadores logísticos nacionales para asegurar que tu pedido llegue en perfectas condiciones."],
                ["¿Puedo retirar mi pedido por la bodega?", "Sí, puedes seleccionar la opción de retiro en nuestra bodega ubicada en [direccion] sin costo adicional. Te avisaremos cuando esté listo."],
                ["¿Tienen servicio de delivery en el día?", "En zonas aledañas a [direccion], ofrecemos delivery express. Llámanos al [telefono] para confirmar."],
                ["¿Los vinos llegan bien embalados?", "Sí, utilizamos embalajes especiales y seguros para proteger las botellas durante el transporte."],
                ["¿Cómo hago el seguimiento de mi pedido?", "Una vez despachada tu compra, te enviaremos un código de seguimiento por correo electrónico para que puedas ver el estado de tu envío."],
                ["¿Venden al por mayor?", "Sí, tenemos precios y condiciones especiales para compras mayoristas. Por favor, contacta a nuestro departamento de ventas al [telefono] o en [linkWeb]."],
                ["¿Hay descuentos para restaurantes u hoteles?", "Sí, ofrecemos convenios y tarifas preferenciales para el canal HORECA. Comunícate con nosotros al [telefono]."],
                ["¿Venden vinos internacionales?", "Nos especializamos en vinos de nuestra región, pero ocasionalmente podemos tener algunas etiquetas invitadas. Consulta nuestro catálogo en [linkWeb]."],
                ["¿Aceptan pagos contra entrega?", "Por seguridad y para agilizar los despachos, actualmente solo aceptamos pagos anticipados a través de nuestra web [linkWeb] o por transferencia."],
                ["¿Puedo modificar un pedido ya realizado?", "Si tu pedido aún no ha sido despachado, contáctanos urgentemente al [telefono] e intentaremos ayudarte."],
                ["¿Se puede devolver un vino si llega dañado?", "Sí, por supuesto. Si algún producto llega dañado, por favor contáctanos inmediatamente al [telefono] con fotos del daño para gestionar el reemplazo."],
                ["¿Puedo elegir los vinos dentro de un combo?", "Algunos de nuestros combos son predefinidos para ofrecer el mejor precio, mientras que otros permiten cierta personalización. Revisa las opciones en [linkWeb]."],
                ["¿Hay beneficios si me asocio al club de vinos?", "¡Sí! Nuestro club de vinos ofrece descuentos exclusivos, acceso anticipado a lanzamientos, envíos preferenciales y más. Infórmate en [linkWeb]."],
                ["¿Cuánto cuesta el envío?", "El costo de envío se calcula automáticamente al finalizar tu compra en [linkWeb], según el destino y el peso del pedido."],
                ["¿Hacen envíos a provincias?", "Sí, realizamos envíos a todas las provincias de Argentina."],
                ["¿Puedo hacer una compra como empresa?", "Sí, emitimos factura A y podemos coordinar condiciones especiales para compras corporativas. Contáctanos al [telefono]."],
                ["¿En qué horario entregan los pedidos?", "Las entregas se realizan generalmente en horario comercial, de lunes a viernes entre las 9 y 18 hs, dependiendo de la empresa de logística y la zona."]
            ],
            "Turismo y visitas": [
                ["¿Puedo visitar la bodega?", "¡Sí! Estaremos encantados de recibirte. Ofrecemos visitas guiadas y degustaciones todos los días, pero es necesario reservar con anticipación en [linkWeb] o llamando al [telefono]."],
                ["¿Ofrecen degustaciones?", "Sí, tenemos varias opciones de degustación, desde nuestros vinos clásicos hasta líneas premium y experiencias temáticas. Puedes verlas y reservar en [linkWeb]."],
                ["¿Qué incluye la visita guiada?", "Nuestra visita guiada estándar incluye un recorrido por los viñedos, el área de elaboración, nuestras cavas y finaliza con una degustación de algunos de nuestros vinos destacados."],
                ["¿Cuánto cuesta la visita a la bodega?", "El precio de la visita con degustación varía según la experiencia seleccionada. Puedes consultar las tarifas actualizadas y reservar en [linkWeb]."],
                ["¿Necesito reservar con anticipación?", "Sí, es highly recomendable reservar tu visita y degustación con anticipación, especialmente en temporada alta, para asegurar tu lugar. Hazlo en [linkWeb] o al [telefono]."],
                ["¿Puedo ir sin reserva?", "Podrías tener suerte si hay cancelaciones, pero no podemos garantizar disponibilidad sin reserva previa. Te sugerimos contactarnos antes."],
                ["¿Cuáles son los horarios de visita?", "Nuestros horarios de visita son usualmente de lunes a sábados, con varios turnos disponibles. Consulta los horarios exactos y disponibilidad en [linkWeb] o al [telefono]."],
                ["¿Ofrecen visitas en inglés?", "Sí, contamos con guías bilingües para visitas en inglés y otros idiomas con previa coordinación. Por favor, especifícalo al momento de reservar."],
                ["¿Se puede almorzar en la bodega?", "Sí, tenemos un restaurante que ofrece exquisitos menúes maridados con nuestros vinos. Es imprescindible reservar con antelación a través de [linkWeb] o al [telefono]."],
                ["¿Tienen opciones veganas o sin gluten en el restaurante?", "Sí, nuestro menú contempla opciones para diferentes requerimientos alimenticios, incluyendo veganas y sin gluten. Por favor, avísanos al momento de la reserva."],
                ["¿La visita es apta para niños?", "Los niños son bienvenidos a acompañar en el recorrido por la bodega (las áreas permitidas), pero la degustación de vinos es exclusiva para mayores de 18 años."],
                ["¿Se pueden tomar fotos durante la visita?", "¡Claro! Te alentamos a tomar fotos y compartir tu experiencia en [nombreEmpresa]."],
                ["¿Ofrecen tours privados?", "Sí, podemos organizar visitas y degustaciones privadas y personalizadas para grupos pequeños o parejas. Contáctanos al [telefono] para más información."],
                ["¿La visita es accesible para personas con movilidad reducida?", "Hacemos nuestro mejor esfuerzo para que nuestras instalaciones sean accesibles. Por favor, contáctanos al [telefono] antes de tu visita para coordinar cualquier necesidad específica."],
                ["¿Puedo comprar vinos luego del tour?", "¡Por supuesto! Tenemos una tienda en la bodega donde podrás adquirir todos nuestros vinos, a menudo con precios especiales para visitantes."],
                ["¿Cuánto dura la experiencia completa?", "Una visita guiada con degustación estándar suele durar entre 60 y 90 minutos, pero puede variar según la opción elegida."],
                ["¿Ofrecen transporte desde el hotel?", "No ofrecemos transporte de forma regular, pero podemos ayudarte a coordinar con servicios de traslado locales si lo necesitas. Consúltanos al [telefono]."],
                ["¿Hay promociones para grupos grandes?", "Sí, para grupos de más de 10 personas, ofrecemos tarifas y experiencias especiales. Contacta a nuestro equipo de turismo al [telefono]."],
                ["¿Tienen actividades para empresas?", "Sí, organizamos eventos corporativos, jornadas de team building y catas privadas para empresas. Escríbenos para una propuesta a medida."],
                ["¿Ofrecen experiencias para parejas?", "Tenemos algunas opciones pensadas para parejas, como degustaciones privadas. Puedes consultar en [linkWeb] o llamarnos al [telefono]."],
                ["¿Puedo celebrar mi cumpleaños en la bodega?", "Sería un placer. Contamos con espacios y propuestas para celebraciones. Contáctanos al [telefono] para ver opciones."],
                ["¿Se puede hacer una boda en la bodega?", "Sí, nuestros viñedos y salones son un marco ideal para bodas. Contacta a nuestro equipo de eventos para más información."],
                ["¿Tienen alojamiento en la bodega?", "Actualmente no contamos con alojamiento propio en la bodega principal, pero podemos recomendarte hoteles cercanos en [ubicacion]."],
                ["¿Se puede hacer picnic en los jardines?", "En ciertas épocas del año y con reserva, ofrecemos canastas de picnic para disfrutar en nuestros jardines. Consulta la disponibilidad."],
                ["¿Ofrecen actividades con vendimia?", "Sí, durante la temporada de cosecha (usualmente entre febrero y abril en Mendoza), solemos tener actividades especiales de vendimia para visitantes. Infórmate en [linkWeb]."],
                ["¿Organizan eventos con música en vivo?", "Ocasionalmente organizamos eventos especiales con música. Anunciamos estas actividades en nuestro sitio web [linkWeb] y redes sociales."],
                ["¿Tienen tienda de souvenirs?", "Sí, además de vinos, en nuestra tienda encontrarás accesorios relacionados con el vino y algunos productos regionales."],
                ["¿La experiencia cambia según la estación del año?", "Definitivamente. Cada estación ofrece un paisaje y actividades diferentes en los viñedos y la bodega."],
                ["¿Puedo llevar a mi mascota?", "Por normativas de higiene en áreas de elaboración, las mascotas solo son permitidas en ciertas áreas exteriores designadas. Por favor, consulta antes de traerla."],
                ["¿Hay estacionamiento disponible?", "Sí, contamos con estacionamiento gratuito para nuestros visitantes durante su permanencia en [nombreEmpresa]."]
            ],
            "Información general": [
                ["¿Tienen vinos premiados?", "Sí, estamos orgullosos de que varios de nuestros vinos han recibido reconocimientos y medallas en importantes concursos nacionales e internacionales. Puedes ver algunos en [linkWeb]."],
                ["¿Cuál es el vino más vendido?", "Nuestro Malbec de la línea Reserva suele ser uno de los favoritos por su excelente relación calidad-precio, pero te invitamos a descubrir toda nuestra gama en [linkWeb]."],
                ["¿Puedo hacer consultas por WhatsApp?", "¡Claro! Puedes contactarnos por WhatsApp al [telefono] durante nuestro [horario] y te asistiremos con gusto."],
                ["¿Trabajan con restaurantes?", "Sí, tenemos una relación cercana con el sector gastronómico y ofrecemos condiciones especiales. Los interesados pueden contactarnos al [telefono]."],
                ["¿Dónde están ubicados?", "Nuestra bodega y viñedos principales se encuentran en [direccion], en el corazón de Mendoza. Puedes ver el mapa en [linkWeb]."],
                ["¿Hace cuánto tiempo existe la bodega?", "En [nombreEmpresa] tenemos una rica historia y tradición en la elaboración de vinos, con más de [NumeroAñosTrayectoria] años de experiencia (si tienes este dato, sino omite el número)."],
                ["¿Puedo conocer su historia?", "Por supuesto, te invitamos a leer sobre nuestra trayectoria y filosofía en la sección 'Nosotros' de nuestro sitio web [linkWeb]."],
                ["¿Cómo conservan los vinos?", "Nuestros vinos se conservan en condiciones óptimas de temperatura y humedad en nuestras cavas subterráneas para asegurar su correcta evolución."],
                ["¿Qué tipo de uva cultivan?", "Trabajamos con una variedad de uvas nobles, destacándose el Malbec, Cabernet Sauvignon, Chardonnay y Torrontés, entre otras adaptadas a nuestro terroir."],
                ["¿Usan barricas de roble?", "Sí, para nuestros vinos de alta gama, utilizamos barricas de roble francés y americano durante la crianza para aportar complejidad y estructura."],
                ["¿Cuántas etiquetas tienen?", "Actualmente contamos con un portfolio de más de X etiquetas diferentes, abarcando diversas líneas y estilos (Reemplaza X por el número aproximado o generaliza). Puedes verlas todas en [linkWeb]."],
                ["¿Tienen vinos para regalar?", "Definitivamente. Ofrecemos elegantes estuches, cajas de regalo y la posibilidad de añadir dedicatorias. Visita la sección de regalos en [linkWeb]."],
                ["¿Se puede personalizar una etiqueta?", "Sí, para ocasiones especiales o regalos corporativos, ofrecemos un servicio de personalización de etiquetas. Consulta condiciones al [telefono]."],
                ["¿Tienen vinos espumantes?", "Sí, elaboramos vinos espumantes de alta calidad mediante método tradicional y Charmat. Descúbrelos en [linkWeb]."],
                ["¿Tienen tienda física?", "Sí, además de nuestra tienda online [linkWeb], puedes visitarnos y comprar directamente en nuestra vinoteca en la bodega, ubicada en [direccion]."],
                ["¿Ofrecen cursos o capacitaciones?", "Periódicamente organizamos catas dirigidas, talleres de degustación y cursos introductorios al mundo del vino. Infórmate sobre próximos eventos en [linkWeb]."],
                ["¿Participan en ferias de vinos?", "Sí, [nombreEmpresa] suele estar presente en las principales ferias y eventos vitivinícolas del país y, en ocasiones, internacionales."],
                ["¿Tienen presencia en redes sociales?", "¡Sí! Síguenos en Instagram y Facebook para estar al tanto de nuestras novedades, eventos y promociones. Encuentra los links en [linkWeb]."],
                ["¿Cómo puedo contactar con ustedes?", "Puedes contactarnos a través del formulario en nuestro sitio web [linkWeb], por email, llamando al [telefono] o vía WhatsApp."],
                ["¿El vino tiene fecha de vencimiento?", "El vino no tiene fecha de vencimiento como otros productos, pero sí una ventana de consumo óptima. Nuestros vinos de guarda pueden evolucionar favorablemente por muchos años si se conservan adecuadamente."],
                ["¿Tienen línea de vinos jóvenes?", "Sí, contamos con líneas de vinos jóvenes, frescos y frutados, ideales para disfrutar a diario. Explora las opciones en [linkWeb]."],
                ["¿Qué diferencia hay entre reserva y gran reserva?", "Generalmente, un 'Gran Reserva' ha tenido un mayor tiempo de crianza en barricas de roble y posterior estiba en botella que un 'Reserva', resultando en vinos de mayor complejidad y potencial de guarda."],
                ["¿Venden a todo el país?", "Sí, a través de nuestra tienda online [linkWeb] realizamos envíos seguros a todas las provincias de Argentina."],
                ["¿Qué tipo de tapones usan?", "Utilizamos diferentes tipos de tapones según la línea de vino y su potencial de guarda, incluyendo corcho natural de alta calidad, tapones técnicos y tapa a rosca para vinos jóvenes."],
                ["¿Tienen vinos dulces?", "Sí, elaboramos algunos vinos de cosecha tardía o dulces naturales. Puedes consultar la disponibilidad actual en [linkWeb]."],
                ["¿El vino debe guardarse acostado?", "Se recomienda guardar las botellas acostadas, especialmente aquellas con tapón de corcho natural, para mantener el corcho húmedo y asegurar un buen sellado."],
                ["¿Tienen línea orgánica?", "Actualmente estamos desarrollando nuestra línea orgánica. Consulta en [linkWeb] o al [telefono] por las últimas novedades al respecto."],
                ["¿Dónde se pueden conseguir sus vinos?", "Además de nuestra tienda online [linkWeb] y la vinoteca en la bodega ([direccion]), nuestros vinos se encuentran en vinotecas seleccionadas y algunos supermercados y restaurantes."],
                ["¿Qué premios han ganado?", "Nuestros vinos han sido reconocidos en diversos concursos. Mencionamos algunos de los más recientes en nuestro sitio web [linkWeb] en la sección de reconocimientos."],
                ["¿Qué distingue a sus vinos?", "En [nombreEmpresa] buscamos la máxima expresión de nuestro terroir en [ubicacion], combinando tradición con innovación para crear vinos con identidad, elegancia y carácter."]
            ]
        }
    },
    "almacen": {
        "nombre": "Almacén",
        "descripcion": "Comercio de cercanía con productos de consumo diario, bebidas, alimentos y artículos básicos.",
        "categorias": {
            "Productos y stock": [
                ["¿Qué productos venden en el almacén?", "En [nombreEmpresa] tenemos una gran variedad de alimentos, bebidas, productos de limpieza, artículos de perfumería y mucho más para tu día a día. ¡Visítanos en [direccion]!"],
                ["¿Tienen productos sin TACC?", "Sí, contamos con una sección de productos aptos para celíacos, debidamente identificados. Pregunta a nuestro personal en [direccion] o consulta al [telefono]."],
                ["¿Venden productos veganos?", "Sí, ofrecemos diversas opciones veganas, desde alimentos hasta productos de cuidado personal. Ven a [direccion] y descúbrelos."],
                ["¿Tienen frutas y verduras frescas?", "Sí, recibimos frutas y verduras frescas de estación regularmente. La calidad es nuestra prioridad."],
                ["¿Hay panadería o pan fresco?", "Sí, tenemos pan fresco del día y una selección de productos de panadería. Nuestro [horario] incluye la llegada del pan."],
                ["¿Venden bebidas alcohólicas?", "Sí, ofrecemos una selección de cervezas, vinos y otras bebidas con alcohol para mayores de 18 años."],
                ["¿Tienen productos de limpieza?", "Contamos con una línea completa de productos de limpieza para el hogar de primeras marcas y opciones económicas."],
                ["¿Puedo comprar artículos de higiene personal?", "Sí, encontrarás jabones, shampoo, desodorantes, pasta dental y otros artículos de higiene personal en [nombreEmpresa]."],
                ["¿Hay comida para mascotas?", "Sí, tenemos alimento balanceado y algunos accesorios para perros y gatos."],
                ["¿Venden productos light o dietéticos?", "Disponemos de una variedad de productos bajos en sodio, sin azúcar agregada, light y dietéticos. Consulta en [direccion]."],
                ["¿Tienen lácteos y fiambres?", "Sí, nuestra fiambrería y sector de lácteos ofrecen variedad de quesos, yogures, leches y fiambres frescos cortados en el momento."],
                ["¿Reponen stock todos los días?", "Sí, recibimos mercadería y reponemos stock diariamente para asegurar la disponibilidad de tus productos favoritos."],
                ["¿Qué marcas manejan?", "Trabajamos con una amplia gama de marcas, desde las más reconocidas hasta opciones de excelente relación calidad-precio."],
                ["¿Tienen combos o packs?", "Sí, frecuentemente armamos combos y packs de productos con descuentos especiales. Pregunta en caja o al [telefono]."],
                ["¿Venden artículos escolares?", "Durante la temporada escolar, ofrecemos útiles básicos como cuadernos, lápices y otros elementos. Consulta disponibilidad."],
                ["¿Hay productos de temporada?", "Sí, incorporamos productos especiales según la temporada, como artículos para Pascuas, Navidad, o productos típicos de verano/invierno."],
                ["¿Tienen productos orgánicos?", "Contamos con una selección creciente de productos orgánicos y naturales. Búscalos en nuestras góndolas."],
                ["¿Venden snacks y golosinas?", "¡Por supuesto! Tenemos una gran variedad de snacks, galletitas, chocolates, caramelos y otras golosinas."],
                ["¿Cuentan con productos congelados?", "Sí, ofrecemos productos congelados como verduras, hamburguesas, empanadas y helados."],
                ["¿Tienen productos de almacén por mayor?", "Para algunos productos podemos ofrecer precios por cantidad o bulto cerrado. Consulta con nuestro personal en [direccion]."],
                ["¿Hay productos para celíacos certificados?", "Sí, todos nuestros productos sin TACC están claramente identificados y cumplen con las certificaciones correspondientes."],
                ["¿Qué tipo de aceites tienen?", "Ofrecemos aceite de girasol, mezcla, oliva en varias presentaciones y marcas, y también aceite en spray."],
                ["¿Tienen productos sin azúcar?", "Sí, contamos con una línea de productos sin azúcar agregada, como jugos, galletas y dulces."],
                ["¿Venden carbón o leña?", "Sí, usualmente tenemos carbón y leña disponibles, especialmente los fines de semana."],
                ["¿Cuentan con pilas o artículos de ferretería?", "Tenemos pilas de varios tamaños y algunos artículos básicos de ferretería como bombitas o cinta adhesiva."]
            ],
            "Métodos de pago": [
                ["¿Aceptan tarjeta de crédito?", "Sí, en [nombreEmpresa] aceptamos las principales tarjetas de crédito como Visa, Mastercard, American Express, entre otras."],
                ["¿Puedo pagar con débito?", "Sí, todas las tarjetas de débito son bienvenidas."],
                ["¿Tienen posnet?", "Sí, contamos con terminal de cobro electrónico (posnet) para pagos con tarjeta y billeteras virtuales."],
                ["¿Aceptan MercadoPago?", "¡Claro! Podés abonar con tu cuenta de MercadoPago escaneando nuestro código QR en caja."],
                ["¿Puedo pagar con Cuenta DNI?", "Sí, aceptamos pagos con la aplicación Cuenta DNI y sus beneficios cuando están vigentes."],
                ["¿Se puede pagar con transferencia?", "Sí, aceptamos transferencias bancarias. Puedes mostrar el comprobante en caja o enviarlo a nuestro [telefono] (WhatsApp)."],
                ["¿Hacen descuento por pago en efectivo?", "Sí, usualmente ofrecemos un pequeño descuento por pago en efectivo. ¡Consulta en caja!"],
                ["¿Puedo pagar con QR?", "Sí, puedes pagar con código QR a través de MercadoPago u otras billeteras virtuales compatibles."],
                ["¿Aceptan pagos con tarjeta alimentaria?", "Sí, aceptamos la Tarjeta Alimentar y otras tarjetas de programas sociales habilitadas para la compra de alimentos."],
                ["¿Tienen cuotas sin interés?", "Ocasionalmente tenemos promociones de cuotas sin interés con algunos bancos o tarjetas. Consulta las promociones vigentes."],
                ["¿Aceptan billeteras virtuales?", "Sí, además de MercadoPago, aceptamos otras billeteras virtuales como MODO, Ualá, Naranja X, entre otras."],
                ["¿Puedo pagar online antes de retirar?", "Si haces tu pedido por [telefono] (WhatsApp), puedes coordinar el pago por transferencia o link de pago antes de pasar a retirar por [direccion]."],
                ["¿Entregan factura por compras?", "Sí, emitimos factura B a consumidor final. Si necesitas factura A, por favor solicítala con tu CUIT antes de finalizar la compra."],
                ["¿Puedo pedir factura electrónica?", "Sí, todas nuestras facturas pueden ser enviadas a tu correo electrónico si lo deseas."],
                ["¿Se puede pagar en dólares?", "Preferentemente operamos en pesos argentinos. Para casos excepcionales, consulta con el encargado en [direccion]."],
                ["¿Ofrecen promociones bancarias?", "Sí, estamos atentos a las promociones bancarias y solemos adherirnos a los descuentos y reintegros que ofrecen los bancos."],
                ["¿Tienen promociones con tarjetas?", "Sí, a menudo hay promociones específicas con ciertas tarjetas o en días particulares. Pregunta a nuestro personal o revisa nuestras comunicaciones."],
                ["¿Qué medios de pago NO aceptan?", "Generalmente no aceptamos cheques personales ni tarjetas de crédito o débito que no estén habilitadas en Argentina."],
                ["¿Aceptan pagos con criptomonedas?", "Por el momento no aceptamos pagos con criptomonedas, pero estamos evaluando opciones a futuro."],
                ["¿Se puede pagar al recibir en el domicilio (delivery)?", "Sí, para nuestros envíos a domicilio puedes abonar en efectivo o con posnet móvil al recibir tu pedido. Confirma al hacer tu pedido por [telefono]."],
                ["¿El delivery tiene un costo adicional según el método de pago?", "No, el costo del envío es independiente del método de pago que elijas."],
                ["¿Hay un monto mínimo para pagar con tarjeta?", "Para compras pequeñas preferimos efectivo o débito, pero consulta en caja por el mínimo actual para crédito si lo hubiera."],
                ["¿Puedo abonar con distintas formas de pago una misma compra?", "Sí, puedes pagar una parte en efectivo y otra con tarjeta, por ejemplo. Avísanos en caja."],
                ["¿Hay promociones si soy cliente frecuente?", "¡Valoramos a nuestros clientes! Pregunta por nuestros programas de fidelización o descuentos para clientes habituales."],
                ["¿Aceptan pagos con QR de la app del banco?", "Sí, si tu aplicación bancaria permite pagos con QR interoperable, podrás usarla en nuestro local."]
            ],
            "Horarios y envíos": [
                ["¿Cuál es el horario de atención?", "En [nombreEmpresa] nuestro horario es [horario]. ¡Te esperamos!"],
                ["¿Abren los feriados?", "Generalmente abrimos los feriados en un horario especial, usualmente medio día. Te recomendamos consultar nuestro [linkWeb] o llamar al [telefono] para confirmar."],
                ["¿Hacen envíos a domicilio?", "Sí, realizamos envíos a domicilio en la zona de [ubicacion]. Puedes hacer tu pedido por [telefono] (WhatsApp)."],
                ["¿Hay un mínimo de compra para envíos?", "Sí, para el servicio de delivery tenemos un monto mínimo de compra. Consulta al [telefono] cuál es el mínimo actual."],
                ["¿Qué zonas cubren con delivery?", "Cubrimos la zona céntrica y varios barrios aledaños a [direccion]. Confirma si llegamos a tu dirección llamando al [telefono]."],
                ["¿Cuánto cuesta el envío?", "El costo del envío varía según la distancia desde nuestro local en [direccion]. Es un monto fijo para zonas cercanas, consúltanos."],
                ["¿Cuánto demora el envío?", "Intentamos que la demora sea la menor posible, usualmente entre 30 y 90 minutos, dependiendo de tu ubicación y la cantidad de pedidos."],
                ["¿Puedo elegir el horario de entrega?", "Sí, al hacer tu pedido por [telefono], puedes coordinar una franja horaria de entrega que te sea conveniente."],
                ["¿Tienen envíos programados?", "¡Claro! Puedes hacer tu pedido con anticipación y programar la entrega para más tarde o para otro día."],
                ["¿Puedo hacer pedidos por WhatsApp?", "Sí, es nuestra forma preferida para pedidos de delivery. Escríbenos al [telefono]."],
                ["¿Puedo pasar a retirar por el local?", "Por supuesto, puedes hacer tu pedido por [telefono] y pasar a retirarlo por [direccion] en nuestro [horario]."],
                ["¿Entregan pedidos en el día?", "Sí, todos los pedidos para delivery realizados con suficiente antelación se entregan en el mismo día."],
                ["¿El delivery es propio o tercerizado?", "Contamos con repartidores propios para asegurar un servicio de entrega rápido y cuidadoso."],
                ["¿Puedo hacer un pedido urgente?", "Si necesitas un pedido con urgencia, llámanos al [telefono] y haremos lo posible por priorizarlo según nuestra disponibilidad."],
                ["¿Hay envíos gratuitos?", "Ocasionalmente tenemos promociones de envío gratuito superando cierto monto de compra. Consulta nuestras ofertas vigentes."],
                ["¿Hacen envíos los domingos?", "Nuestro servicio de delivery los domingos puede ser limitado o tener un horario especial. Por favor, consulta al [telefono]."],
                ["¿Cómo sé si mi pedido está en camino?", "Te avisaremos por WhatsApp cuando tu pedido salga de [nombreEmpresa] hacia tu domicilio."],
                ["¿Qué pasa si no estoy cuando llega el pedido?", "Nos comunicaremos contigo al [telefono] que nos dejaste para coordinar una nueva entrega o ver si alguien más puede recibirlo."],
                ["¿Se puede pagar al recibir?", "Sí, para los pedidos de delivery puedes pagar en efectivo o con tarjeta/QR al momento de la entrega."],
                ["¿Puedo cancelar un pedido?", "Puedes cancelar tu pedido siempre que nos avises al [telefono] antes de que haya salido a reparto."],
                ["¿Los productos llegan bien embalados?", "Sí, preparamos cada pedido con cuidado para que todos los productos lleguen en perfectas condiciones a tu hogar."],
                ["¿Entregan a oficinas o comercios?", "Sí, realizamos entregas en oficinas y otros comercios dentro de nuestra zona de cobertura."],
                ["¿Cuántas veces por día hacen envíos?", "Realizamos varios despachos de delivery a lo largo de nuestro [horario] de atención, según la demanda."],
                ["¿Puedo modificar mi pedido una vez enviado?", "Una vez que el pedido está en camino, es difícil modificarlo. Llámanos al [telefono] lo antes posible si necesitas un cambio urgente."],
                ["¿El repartidor puede ayudarme a subir el pedido?", "Nuestros repartidores harán lo posible por ayudarte dentro de sus posibilidades y si no implica riesgos o demoras excesivas."]
            ],
            "Atención al cliente": [
                ["¿Tienen servicio de atención al cliente?", "¡Sí! En [nombreEmpresa] valoramos tu opinión. Puedes comunicarte con nosotros por WhatsApp al [telefono], llamarnos, o hablar con nuestro personal en [direccion]."],
                ["¿Dónde puedo hacer un reclamo?", "Si tienes algún reclamo, por favor contáctanos por WhatsApp al [telefono] con los detalles y tu comprobante de compra, o acércate a [direccion]."],
                ["¿Puedo devolver un producto?", "Aceptamos devoluciones de productos cerrados, en perfecto estado y con el comprobante de compra, dentro de un plazo razonable. Consulta nuestra política en [direccion]."],
                ["¿Cuánto tiempo tengo para hacer una devolución?", "El plazo para devoluciones de productos no perecederos suele ser de unos días. Para productos frescos, es inmediato. Consulta en [direccion]."],
                ["¿Hacen cambios de productos vencidos?", "Si por error adquieres un producto vencido de nuestras góndolas, te lo cambiaremos sin problemas presentando el comprobante."],
                ["¿Qué pasa si recibo un producto equivocado en mi delivery?", "Por favor, comunícate inmediatamente con nosotros al [telefono] y solucionaremos el error enviándote el producto correcto lo antes posible."],
                ["¿Atienden reclamos por redes sociales?", "Si bien preferimos el contacto directo por [telefono] para reclamos, también estamos atentos a nuestros mensajes en redes sociales. Encuéntranos en [linkWeb]."],
                ["¿Tienen número de teléfono directo?", "Sí, nuestro número de atención es el [telefono]. Puedes llamar durante nuestro [horario]."],
                ["¿Hay alguien encargado del servicio al cliente?", "Todo nuestro personal en [direccion] está capacitado para ayudarte, y puedes pedir hablar con un encargado si es necesario."],
                ["¿Puedo pedir una factura corregida?", "Sí, si necesitas corregir datos en tu factura, acércate a [direccion] con el comprobante original y lo solucionamos."],
                ["¿Puedo hablar con un supervisor?", "Por supuesto, si tienes una situación que requiere la atención de un supervisor, nuestro personal en [direccion] te comunicará."],
                ["¿Responden los mensajes fuera del horario comercial?", "Los mensajes recibidos fuera de nuestro [horario] se responden con prioridad al siguiente día hábil."],
                ["¿Puedo hacer un pedido personalizado o encargar algo que no tienen?", "Si buscas algún producto en particular que no tenemos habitualmente, consúltanos al [telefono]. Haremos lo posible por conseguirlo para ti."],
                ["¿Hacen envíos con comprobante?", "Sí, todos nuestros envíos a domicilio se entregan con el ticket o factura correspondiente a tu compra."],
                ["¿Los productos tienen garantía?", "Los productos elaborados o frescos tienen garantía de calidad al momento de la entrega. Para productos envasados, aplica la garantía del fabricante."],
                ["¿Puedo pedir que revisen un cobro si creo que hay un error?", "Absolutamente. Acércate a [direccion] con tu comprobante y revisaremos cualquier diferencia en el cobro."],
                ["¿Qué pasa si no recibo todo lo que pedí en el delivery?", "Comunícate al [telefono] de inmediato. Verificaremos tu pedido y te enviaremos los productos faltantes o coordinaremos un reembolso."],
                ["¿Atienden consultas en el local?", "Sí, nuestro personal en [direccion] está siempre dispuesto a ayudarte con tus consultas y a encontrar lo que necesitas."],
                ["¿Puedo hacer un pedido con ayuda del personal si voy al local?", "¡Claro que sí! Si necesitas ayuda para armar tu compra o encontrar productos, nuestro equipo en [direccion] te asesorará con gusto."],
                ["¿Tienen atención preferencial para personas mayores o con movilidad reducida?", "Sí, en [nombreEmpresa] intentamos dar atención prioritaria a adultos mayores, embarazadas y personas con movilidad reducida."],
                ["¿Ofrecen productos recomendados según mi necesidad?", "Sí, si nos cuentas qué estás buscando o qué necesitas cocinar, nuestro personal puede recomendarte los mejores productos."],
                ["¿Hay alguien que me pueda armar una lista semanal de compras?", "Si te haces cliente habitual, podemos ayudarte a recordar tus compras frecuentes o armar una lista base para tus pedidos por [telefono]."],
                ["¿Guardan historial de pedidos?", "Si realizas tus pedidos por WhatsApp o te identificas como cliente, podemos tener un registro de tus compras anteriores para facilitar futuros pedidos."],
                ["¿Se puede hacer una suscripción semanal o quincenal de productos?", "Actualmente no tenemos un sistema formal de suscripción, pero podemos coordinar pedidos recurrentes si nos contactas al [telefono]."],
                ["¿Me pueden avisar si llega un producto que busco y no tienen en stock?", "Sí, déjanos tus datos y el producto que buscas, y te avisaremos por [telefono] apenas lo recibamos."]
            ]
        }
    },
    "local_comercial": {
        "nombre": "Local Comercial",
        "descripcion": "Tiendas físicas que venden productos al público: indumentaria, tecnología, regalos, etc.",
        "categorias": {
            "Productos y servicios": [
                ["¿Tienen accesorios nuevos?", "Sí, en [nombreEmpresa] renovamos nuestro stock de accesorios todas las semanas con las últimas tendencias y novedades. ¡Visítanos en [direccion]!"],
                ["¿Reparan celulares?", "Ofrecemos servicio técnico para celulares en algunos de nuestros locales o a través de asociados. Consulta en [direccion] o al [telefono] por detalles."],
                ["¿Hacen composturas de ropa?", "Sí, realizamos arreglos y composturas de ropa como ruedos, cambios de cierre y ajustes. Trae tu prenda a [direccion]."],
                ["¿Tienen productos personalizados?", "¡Sí! Personalizamos una variedad de artículos como tazas, remeras, y más. Ideal para regalos. Consulta opciones y tiempos en [nombreEmpresa]."],
                ["¿Puedo encargar un ramo especial de flores?", "Si nuestro local incluye florería, claro que sí. Hacemos ramos a pedido para toda ocasión. Llámanos al [telefono]."],
                ["¿Venden estuches para celular?", "Sí, tenemos una amplia gama de estuches, fundas y protectores para la mayoría de los modelos de celular. Encuéntralos en [direccion]."],
                ["¿Tienen mochilas o carteras?", "Contamos con una variada selección de mochilas, carteras, bolsos y marroquinería de diferentes estilos y marcas."],
                ["¿Hacen combos o kits de regalo?", "Sí, podemos armar combos o kits de regalo personalizados con los productos que elijas. Perfecto para cualquier ocasión."],
                ["¿Ofrecen productos ecológicos o sustentables?", "Intentamos incorporar cada vez más opciones ecológicas y sustentables. Pregunta a nuestro personal por la línea disponible en [nombreEmpresa]."],
                ["¿Venden ropa para niños?", "Sí, tenemos una sección de indumentaria infantil con ropa para todas las edades y estilos. Visita [direccion]."],
                ["¿Tienen plantas o suculentas?", "En algunos de nuestros locales, especialmente los de regalos y deco, ofrecemos una selección de plantas, suculentas y arreglos verdes."],
                ["¿Venden auriculares o parlantes?", "Sí, contamos con accesorios de tecnología como auriculares, parlantes Bluetooth y otros gadgets. Encuéntralos en [nombreEmpresa]."],
                ["¿Hacen grabados personalizados?", "Para ciertos productos como joyería o regalos metálicos, ofrecemos servicio de grabado. Consulta en [direccion] por disponibilidad y costos."],
                ["¿Tienen kits escolares en temporada?", "Sí, durante la época de inicio de clases, preparamos kits escolares con los útiles esenciales. Consulta en nuestro [horario] de atención."],
                ["¿Puedo encargar productos por catálogo si no los veo en el local?", "Sí, muchos de nuestros productos se pueden encargar si no están en exhibición. Consulta nuestro catálogo en [linkWeb] o pregunta al [telefono]."],
                ["¿Ofrecen juguetes didácticos?", "Contamos con una selección de juguetes didácticos y recreativos para diferentes edades, fomentando el aprendizaje y la diversión."],
                ["¿Venden fundas para notebooks o tablets?", "Sí, tenemos fundas, maletines y mochilas diseñadas para proteger tus dispositivos electrónicos como notebooks y tablets."],
                ["¿Tienen productos de temporada (Navidad, Día de la Madre, etc.)?", "¡Definitivamente! Adaptamos nuestro stock y ofrecemos productos especiales para todas las fechas importantes y temporadas del año."],
                ["¿Hay productos en oferta hoy?", "Siempre tenemos algunas promociones o productos seleccionados en oferta. Visita [direccion] o consulta nuestro [linkWeb] para ver las ofertas del día."],
                ["¿Tienen productos para cumpleaños (decoración, regalos)?", "Sí, encontrarás una variedad de artículos de decoración para fiestas, tarjetas de cumpleaños y muchas opciones originales para regalar."],
                ["¿Hacen bordados personalizados en ropa o accesorios?", "Para algunos artículos textiles, ofrecemos servicio de bordado personalizado. Consulta en [nombreEmpresa] por esta opción."],
                ["¿Venden productos nacionales o de emprendedores locales?", "Sí, en [nombreEmpresa] valoramos y apoyamos a los productores y emprendedores argentinos, ofreciendo muchos artículos de origen nacional."],
                ["¿Puedo encargar talles grandes o especiales si no los encuentro?", "Hacemos lo posible por tener variedad de talles. Si no encuentras el tuyo, consúltanos al [telefono]; a veces podemos conseguirlo por encargo."],
                ["¿Tienen velas aromáticas, sahumerios o ambientadores?", "Sí, ofrecemos una línea de productos para aromatizar y decorar el hogar, incluyendo velas, sahumerios, difusores y más."],
                ["¿Hay productos para hombres y mujeres en todas las categorías?", "Sí, intentamos tener una oferta equilibrada con productos y estilos tanto para hombres como para mujeres en la mayoría de nuestras secciones."]
            ],
            "Formas de pago": [
                ["¿Aceptan tarjeta de crédito y débito?", "Sí, en [nombreEmpresa] puedes abonar con todas las principales tarjetas de crédito y débito."],
                ["¿Puedo pagar con QR de MercadoPago o MODO?", "¡Claro! Aceptamos pagos con código QR de MercadoPago, MODO y otras billeteras virtuales compatibles."],
                ["¿Tienen cuotas sin interés? ¿Con qué bancos o tarjetas?", "Sí, frecuentemente ofrecemos planes de cuotas sin interés, especialmente con tarjetas de bancos adheridos o en promociones especiales. Consulta en [direccion] o en [linkWeb]."],
                ["¿Trabajan con Ahora 12, Ahora 18 u otros planes del gobierno?", "Solemos adherirnos a los planes de fomento al consumo como Ahora 12. Consulta la vigencia y productos aplicables en [nombreEmpresa]."],
                ["¿Hay descuento por pago en efectivo o transferencia?", "Sí, generalmente ofrecemos un descuento especial por pago en efectivo o transferencia bancaria directa. ¡Pregúntanos!"],
                ["¿Qué medios de pago aceptan para compras online o telefónicas?", "Para compras a distancia a través de [linkWeb] o [telefono], aceptamos MercadoPago, transferencias y a veces coordinamos pago con tarjeta."],
                ["¿Aceptan dólares u otra moneda extranjera?", "Principalmente operamos en pesos argentinos. Para pagos en dólares u otra moneda, consulta la posibilidad y tipo de cambio con nuestro personal en [direccion]."],
                ["¿Se puede señar un producto y pagar el resto después?", "Sí, para muchos productos puedes dejar una seña y completar el pago al momento de retirarlo o antes del envío. Consulta las condiciones."]
            ],
            "Horarios y ubicación": [
                ["¿A qué hora abren y cierran?", "Nuestro horario de atención en [nombreEmpresa] es [horario]. ¡Te esperamos!"],
                ["¿Cuál es su horario de atención los sábados/domingos?", "Los sábados nuestro horario es [horario]. Algunos domingos abrimos en horarios especiales, especialmente en fechas festivas. Consulta en [linkWeb] o [telefono]."],
                ["¿Están abiertos los feriados? ¿Qué horario?", "Dependiendo del feriado, podemos tener horario normal, reducido o permanecer cerrados. Es mejor consultar nuestro [linkWeb] o llamar al [telefono] para confirmar."],
                ["¿Dónde están ubicados? ¿Dirección exacta?", "Nuestra tienda [nombreEmpresa] se encuentra en [direccion]. Puedes ver un mapa y más detalles en [linkWeb]."],
                ["¿Cómo llego al local en transporte público o auto?", "Nuestra ubicación en [direccion] es accesible. En [linkWeb] puedes encontrar indicaciones o consultarnos por las mejores rutas o líneas de colectivo."],
                ["¿Tienen sucursales? ¿Dónde?", "Actualmente, nuestra tienda principal es la de [direccion]. Si tenemos otras sucursales, estarán listadas en [linkWeb]."],
                ["¿Cuál es el teléfono de contacto o WhatsApp?", "Puedes contactarnos llamando al [telefono] o por WhatsApp al mismo número durante nuestro [horario]."],
                ["¿Hay estacionamiento cerca?", "Sí, usualmente hay opciones de estacionamiento en las calles aledañas a [direccion] o playas de estacionamiento privadas cercanas."],
                ["¿Es un local a la calle o en galería?", "Nuestra tienda en [direccion] es un local a la calle, de fácil acceso."]
            ],
            "Políticas de cambios": [
                ["¿Si compro algo y no me gusta o no me sirve, lo puedo cambiar?", "Sí, en [nombreEmpresa] puedes cambiar los productos dentro de los 30 días de la compra, presentando el ticket y con el producto en perfectas condiciones y su empaque original."],
                ["¿Cuál es la política de cambios y devoluciones?", "Nuestra política detallada de cambios y devoluciones está disponible en [linkWeb] o puedes consultarla en nuestro local en [direccion]."],
                ["¿Cuánto tiempo tengo para realizar un cambio?", "Tienes hasta 30 días corridos desde la fecha de compra para realizar un cambio."],
                ["¿Necesito el ticket para el cambio?", "Sí, es indispensable presentar el ticket de compra o el comprobante de regalo para cualquier cambio."],
                ["¿Los productos en oferta tienen cambio?", "Los productos comprados en oferta o liquidación pueden tener condiciones especiales de cambio. Por favor, consulta al momento de la compra o en nuestra política en [linkWeb]."],
                ["¿Hacen devoluciones de dinero?", "Generalmente ofrecemos cambios por otros productos o una nota de crédito por el valor de la compra. Las devoluciones de dinero se evalúan caso por caso según la ley de defensa al consumidor."],
                ["¿Los productos tienen garantía? ¿Cómo funciona?", "Todos nuestros productos nuevos tienen garantía legal. La duración y condiciones pueden variar según el fabricante y el tipo de producto. Consérva tu factura."],
                ["Compré [producto] y tiene una falla, ¿qué hago?", "Si tu producto presenta una falla dentro del período de garantía, por favor acércate a [direccion] con el producto y tu factura para que podamos evaluarlo y ofrecerte una solución."]
            ]
        }
    }
}