faq_data = {
    "medico": {
        "nombre": "Médico General",
        "descripcion": "Consultas clínicas, atención primaria y orientación general de salud.",
        "categorias": {
            "General": [
    ["¿Atienden con obra social?", "Sí, trabajamos con las principales obras sociales del país."],
    ["¿Atienden sin turno?", "Recomendamos sacar turno, pero también atendemos urgencias."],
    ["¿Realizan controles de rutina?", "Sí, hacemos chequeos generales, clínicos y derivaciones si es necesario."],
    ["¿Atienden urgencias?", "Sí, contamos con atención médica inmediata ante emergencias."],
    ["¿Hacen certificados médicos?", "Sí, realizamos certificados de salud, escolares y laborales."],
    ["¿Cuánto cuesta una consulta?", "La consulta tiene un valor estimado, pero puede variar según la cobertura médica o la complejidad del caso."],
    ["¿Atienden a domicilio?", "Sí, ofrecemos atención médica domiciliaria en casos especiales o a pedido."],
    ["¿Recetan medicamentos?", "Sí, prescribimos tratamientos médicos luego de la consulta."],
    ["¿Puedo pagar con tarjeta?", "Sí, aceptamos tarjeta de débito, crédito, transferencias y billeteras virtuales."],
    ["¿Tienen horarios extendidos?", "Sí, atendemos hasta las 20 hs de lunes a viernes y sábados por la mañana."],
    ["¿Puedo pedir turno online?", "Sí, podés reservar turno desde nuestra web o por WhatsApp."],
    ["¿Realizan electrocardiogramas?", "Sí, contamos con equipamiento para ECG y otros estudios básicos."],
    ["¿Pueden derivar a especialistas?", "Sí, hacemos derivaciones según el diagnóstico médico inicial."],
    ["¿Tienen historia clínica digital?", "Sí, registramos todas las consultas en una plataforma segura y digital."],
    ["¿Atención con prepaga?", "Sí, trabajamos con prepagas líderes del país."],
    ["¿Atienden niños y adultos?", "Sí, realizamos atención clínica para todas las edades."],
    ["¿Toman presión y controlan glucosa?", "Sí, hacemos controles básicos como presión arterial, glucemia y saturación de oxígeno."],
    ["¿Vacunan en el consultorio?", "Sí, aplicamos vacunas del calendario y otras recomendadas, según disponibilidad."],
    ["¿Hacen certificados para actividades físicas?", "Sí, realizamos certificados de aptitud física con evaluación médica."],
    ["¿Tienen servicio de nutricionista?", "Sí, contamos con profesionales especializados en nutrición y dietética."],
    ["¿Atienden los fines de semana?", "Atendemos los sábados por la mañana. Consultá disponibilidad para domingos o feriados."],
    ["¿Ofrecen seguimiento de enfermedades crónicas?", "Sí, realizamos controles periódicos para hipertensión, diabetes, entre otras."],
    ["¿Atienden por videollamada?", "Sí, ofrecemos consultas virtuales para casos no urgentes."],
    ["¿Se puede cambiar o cancelar un turno?", "Sí, podés reprogramar o cancelar tu turno con al menos 12 horas de anticipación."],
    ["¿Qué documentación debo llevar a la consulta?", "Solo tu DNI y credencial de obra social o prepaga si tenés. Estudios previos si aplica."],
    ["¿Realizan análisis clínicos?", "Trabajamos con laboratorios asociados. Podés hacerte extracciones y recibir resultados por email."],
    ["¿Hacen estudios ginecológicos o PAP?", "Sí, contamos con profesionales que realizan PAP, colposcopías y controles ginecológicos."],
    ["¿Tienen atención pediátrica?", "Sí, ofrecemos atención clínica para niños desde los primeros meses de vida."],
    ["¿Puedo consultar por dolor de cabeza o malestar general?", "Sí, evaluamos síntomas comunes y orientamos sobre el tratamiento adecuado."],
    ["¿Atienden a personas mayores?", "Sí, tenemos experiencia en atención geriátrica y cuidado integral para adultos mayores."]
]

        }
    },
    "bodega": {
        "nombre": "Bodega",
        "descripcion": "Venta de vinos, enoturismo, degustaciones y atención a clientes mayoristas y minoristas.",
        "categorias": {
            "Ventas y envíos": [
    ["¿Qué tipos de vinos ofrecen?", "Ofrecemos vinos tintos, blancos, rosados, espumantes y especiales de autor."],
    ["¿Tienen tienda online?", "Sí, podés comprar en nuestra tienda virtual las 24 hs con envíos a todo el país."],
    ["¿Hacen envíos a domicilio?", "Sí, enviamos a domicilio en todo el país y también al exterior por pedido especial."],
    ["¿Venden vinos por caja?", "Sí, tenemos descuentos exclusivos por compra en caja cerrada."],
    ["¿Qué medios de pago aceptan?", "Aceptamos tarjetas de débito, crédito, transferencia bancaria y MercadoPago."],
    ["¿Tienen promociones vigentes?", "Sí, ofrecemos combos especiales, descuentos por cantidad y beneficios para socios."],
    ["¿Ofrecen envíos gratis?", "En compras mayores a cierto monto, el envío es gratuito en muchas zonas del país."],
    ["¿Hacen envíos en el día?", "En algunas ciudades sí, dependiendo de la zona y horario de compra."],
    ["¿Cuánto demora el envío?", "De 2 a 5 días hábiles según el destino. En zonas urbanas puede ser más rápido."],
    ["¿Puedo programar el envío para una fecha específica?", "Sí, podés seleccionar la fecha estimada al hacer la compra."],
    ["¿Puedo hacer un regalo a domicilio?", "Sí, ofrecemos cajas especiales con opción de dedicatoria y entrega programada."],
    ["¿Se pueden personalizar las etiquetas?", "Sí, ofrecemos servicio de etiquetas personalizadas para regalos y eventos."],
    ["¿Qué pasa si no hay nadie para recibir el pedido?", "Reprogramamos el envío sin costo adicional la primera vez."],
    ["¿Qué empresas de envío utilizan?", "Trabajamos con operadores logísticos nacionales e internacionales."],
    ["¿Puedo retirar mi pedido por la bodega?", "Sí, contamos con opción de retiro en tienda sin cargo."],
    ["¿Tienen servicio de delivery en el día?", "Sí, en zonas cercanas a la bodega ofrecemos delivery express."],
    ["¿Los vinos llegan bien embalados?", "Sí, usamos embalajes especiales para evitar roturas o filtraciones."],
    ["¿Cómo hago el seguimiento de mi pedido?", "Al despachar tu compra, te enviamos un código de seguimiento por mail."],
    ["¿Venden al por mayor?", "Sí, ofrecemos precios especiales para compras por volumen o mayoristas."],
    ["¿Hay descuentos para restaurantes u hoteles?", "Sí, contamos con convenios especiales para el canal gastronómico."],
    ["¿Venden vinos internacionales?", "Sí, tenemos etiquetas importadas de prestigiosas bodegas extranjeras."],
    ["¿Aceptan pagos contra entrega?", "No, por seguridad solo aceptamos pagos anticipados."],
    ["¿Puedo modificar un pedido ya realizado?", "Sí, siempre que no haya sido despachado. Consultanos urgente."],
    ["¿Se puede devolver un vino si llega dañado?", "Sí, reemplazamos cualquier producto que llegue en mal estado."],
    ["¿Puedo elegir los vinos dentro de un combo?", "En algunos casos sí, según la promoción vigente."],
    ["¿Hay beneficios si me asocio al club de vinos?", "Sí, recibís descuentos, envíos gratuitos y acceso a lanzamientos exclusivos."],
    ["¿Cuánto cuesta el envío?", "El costo varía según destino y cantidad. Se calcula al finalizar la compra."],
    ["¿Hacen envíos a provincias?", "Sí, llegamos a todo el país mediante logística especializada."],
    ["¿Puedo hacer una compra como empresa?", "Sí, facturamos a nombre de empresa y ofrecemos condiciones especiales."],
    ["¿En qué horario entregan los pedidos?", "Depende de la zona, pero generalmente entre 9 y 18 hs."]
],

           "Turismo y visitas": [
    ["¿Puedo visitar la bodega?", "Sí, ofrecemos visitas guiadas todos los días con reserva previa."],
    ["¿Ofrecen degustaciones?", "Sí, tenemos degustaciones clásicas, premium y temáticas para grupos e individuales."],
    ["¿Qué incluye la visita guiada?", "Recorrido por los viñedos, explicación del proceso y degustación de vinos."],
    ["¿Cuánto cuesta la visita a la bodega?", "Depende del tipo de experiencia. Desde $3000 por persona con degustación incluida."],
    ["¿Necesito reservar con anticipación?", "Sí, recomendamos reservar al menos 24 hs antes para asegurar tu lugar."],
    ["¿Puedo ir sin reserva?", "A veces hay lugar, pero sugerimos reservar para garantizar disponibilidad."],
    ["¿Cuáles son los horarios de visita?", "De lunes a sábado, con turnos entre las 10:00 y las 18:00 hs."],
    ["¿Ofrecen visitas en inglés?", "Sí, contamos con guías bilingües. Especificá el idioma al reservar."],
    ["¿Se puede almorzar en la bodega?", "Sí, tenemos restaurante con menú maridado. Requiere reserva previa."],
    ["¿Tienen opciones veganas o sin gluten?", "Sí, nuestro menú contempla opciones para distintas preferencias alimenticias."],
    ["¿La visita es apta para niños?", "Sí, pueden acompañar la visita, pero no participan de las degustaciones."],
    ["¿Se pueden tomar fotos durante la visita?", "Sí, podés sacar fotos en todas las áreas abiertas al público."],
    ["¿Ofrecen tours privados?", "Sí, ofrecemos experiencias exclusivas para parejas o grupos reducidos."],
    ["¿La visita es accesible para personas con movilidad reducida?", "Sí, nuestras instalaciones están adaptadas."],
    ["¿Puedo comprar vinos luego del tour?", "Claro, podés comprar en nuestra tienda al finalizar la visita."],
    ["¿Cuánto dura la experiencia completa?", "Entre 60 y 90 minutos, dependiendo del tipo de tour elegido."],
    ["¿Ofrecen transporte desde el hotel?", "Sí, tenemos servicio de traslado desde ciertos puntos. Consultanos."],
    ["¿Hay promociones para grupos grandes?", "Sí, tenemos precios especiales para grupos de más de 10 personas."],
    ["¿Tienen actividades para empresas?", "Sí, organizamos eventos corporativos, team building y catas privadas."],
    ["¿Ofrecen experiencias para parejas?", "Sí, contamos con paquetes románticos con degustación privada y cena."],
    ["¿Puedo celebrar mi cumpleaños en la bodega?", "Sí, tenemos espacios ideales para celebraciones personales o familiares."],
    ["¿Se puede hacer una boda en la bodega?", "Sí, ofrecemos servicios completos para casamientos en nuestros viñedos."],
    ["¿Tienen alojamiento en la bodega?", "Algunas de nuestras fincas cuentan con hospedaje. Consultá disponibilidad."],
    ["¿Se puede hacer picnic en los jardines?", "Sí, en fechas especiales habilitamos zonas de picnic con canasta incluida."],
    ["¿Ofrecen actividades con vendimia?", "Sí, en temporada podés participar de la cosecha y pisa de uvas."],
    ["¿Organizan eventos con música en vivo?", "Sí, realizamos eventos especiales con artistas locales y DJs."],
    ["¿Tienen tienda de souvenirs?", "Sí, contamos con boutique de vinos, accesorios y productos regionales."],
    ["¿La experiencia cambia según la estación del año?", "Sí, adaptamos actividades y paisajes según temporada."],
    ["¿Puedo llevar a mi mascota?", "Solo se permite el ingreso de mascotas en espacios al aire libre."],
    ["¿Hay estacionamiento disponible?", "Sí, gratuito para visitantes durante el horario de actividades."]
],

            "Información general": [
    ["¿Tienen vinos premiados?", "Sí, varios de nuestros vinos han recibido medallas en concursos internacionales."],
    ["¿Cuál es el vino más vendido?", "Nuestro Malbec Reserva es el favorito por su calidad y precio accesible."],
    ["¿Puedo hacer consultas por WhatsApp?", "Sí, atendemos por WhatsApp de lunes a sábados en horario comercial."],
    ["¿Trabajan con restaurantes?", "Sí, tenemos convenios y precios especiales para el sector gastronómico."],
    ["¿Dónde están ubicados?", "Nuestra bodega está en Mendoza, a pocos minutos del centro."],
    ["¿Hace cuánto tiempo existe la bodega?", "Tenemos más de 20 años de trayectoria en el mercado vitivinícola."],
    ["¿Puedo conocer su historia?", "Claro, en nuestra web hay una sección dedicada a la historia familiar y evolución."],
    ["¿Cómo conservan los vinos?", "Utilizamos bodegas subterráneas y sistemas de temperatura controlada."],
    ["¿Qué tipo de uva cultivan?", "Trabajamos principalmente con Malbec, Cabernet Sauvignon, Chardonnay y Torrontés."],
    ["¿Usan barricas de roble?", "Sí, nuestros vinos reserva se crian en barricas de roble francés y americano."],
    ["¿Cuántas etiquetas tienen?", "Actualmente ofrecemos más de 20 etiquetas en distintas líneas de producto."],
    ["¿Tienen vinos para regalar?", "Sí, ofrecemos estuches premium, cajas personalizadas y opciones para eventos."],
    ["¿Se puede personalizar una etiqueta?", "Sí, ofrecemos etiquetado personalizado para regalos o eventos especiales."],
    ["¿Tienen vinos espumantes?", "Sí, elaboramos espumantes brut, demi sec y rosé según método tradicional."],
    ["¿Tienen tienda física?", "Sí, podés visitarnos en la bodega y comprar directo en nuestra vinoteca."],
    ["¿Ofrecen cursos o capacitaciones?", "Sí, organizamos catas guiadas y talleres de apreciación de vinos."],
    ["¿Participan en ferias de vinos?", "Sí, participamos en ferias nacionales e internacionales todos los años."],
    ["¿Tienen presencia en redes sociales?", "Sí, podés encontrarnos en Instagram, Facebook y LinkedIn."],
    ["¿Cómo puedo contactar con ustedes?", "Desde el sitio web, por WhatsApp o redes sociales. Siempre respondemos."],
    ["¿El vino tiene fecha de vencimiento?", "No vence, pero tiene una guarda recomendada según tipo y añada."],
    ["¿Tienen línea de vinos jóvenes?", "Sí, nuestras líneas jóvenes son frescas y pensadas para consumo diario."],
    ["¿Qué diferencia hay entre reserva y gran reserva?", "El gran reserva tiene más tiempo de crianza en barrica y botella."],
    ["¿Venden a todo el país?", "Sí, hacemos envíos a todo el país desde nuestra tienda online."],
    ["¿Qué tipo de tapones usan?", "Según el producto: corcho natural, sintético o tapa a rosca para líneas jóvenes."],
    ["¿Tienen vinos dulces?", "Sí, contamos con variedades dulces naturales y cosecha tardía."],
    ["¿El vino debe guardarse acostado?", "Sí, especialmente si el tapón es de corcho, para mantener su humedad."],
    ["¿Tienen línea orgánica?", "Sí, contamos con una línea de vinos certificados como orgánicos."],
    ["¿Dónde se pueden conseguir sus vinos?", "En nuestra tienda online, vinotecas seleccionadas y supermercados gourmet."],
    ["¿Qué premios han ganado?", "Medallas en concursos como Decanter, Vinandino y Mundus Vini."],
    ["¿Qué distingue a sus vinos?", "Buscamos equilibrio, expresión varietal y respeto por el terroir mendocino."]
]

        }
    },
    "almacen": {
        "nombre": "Almacén",
        "descripcion": "Comercio de cercanía con productos de consumo diario, bebidas, alimentos y artículos básicos.",
        "categorias": {
           "Productos y stock": [
    ["¿Qué productos venden en el almacén?", "Tenemos alimentos, bebidas, productos de limpieza y artículos de uso diario."],
    ["¿Tienen productos sin TACC?", "Sí, ofrecemos una amplia variedad de productos aptos para celíacos."],
    ["¿Venden productos veganos?", "Sí, contamos con opciones veganas como leches vegetales, snacks y productos sin ingredientes animales."],
    ["¿Tienen frutas y verduras frescas?", "Sí, trabajamos con productores locales para ofrecer frutas y verduras del día."],
    ["¿Hay panadería o pan fresco?", "Sí, recibimos pan fresco todas las mañanas."],
    ["¿Venden bebidas alcohólicas?", "Sí, tenemos cervezas, vinos y algunas bebidas espirituosas."],
    ["¿Tienen productos de limpieza?", "Sí, contamos con una línea completa de artículos de limpieza para el hogar."],
    ["¿Puedo comprar artículos de higiene personal?", "Sí, tenemos jabones, shampoo, pasta dental y más."],
    ["¿Hay comida para mascotas?", "Sí, ofrecemos alimento balanceado para perros y gatos."],
    ["¿Venden productos light o dietéticos?", "Sí, disponemos de productos bajos en sodio, sin azúcar y light."],
    ["¿Tienen lácteos y fiambres?", "Sí, contamos con variedad de quesos, yogures, leche y fiambres."],
    ["¿Reponen stock todos los días?", "Sí, reponemos diariamente según demanda para mantener todo disponible."],
    ["¿Qué marcas manejan?", "Trabajamos con primeras marcas y también opciones económicas."],
    ["¿Tienen combos o packs?", "Sí, armamos packs de productos con descuento todas las semanas."],
    ["¿Venden artículos escolares?", "Sí, tenemos útiles básicos como cuadernos, lápices y cartucheras."],
    ["¿Hay productos de temporada?", "Sí, incorporamos artículos especiales en fechas como Pascuas, Fiestas y vuelta al cole."],
    ["¿Tienen productos orgánicos?", "Sí, ofrecemos algunas opciones naturales y orgánicas."],
    ["¿Venden snacks y golosinas?", "Sí, tenemos chocolates, galletitas, caramelos y más."],
    ["¿Cuentan con productos congelados?", "Sí, tenemos verduras congeladas, hamburguesas, empanadas y helados."],
    ["¿Tienen productos de almacén por mayor?", "Sí, ofrecemos precios especiales para compras grandes."],
    ["¿Hay productos para celíacos certificados?", "Sí, todos los productos sin TACC están debidamente certificados."],
    ["¿Qué tipo de aceites tienen?", "Contamos con aceite de girasol, mezcla, oliva y sprays."],
    ["¿Tienen productos sin azúcar?", "Sí, disponemos de jugos, galletas y dulces sin azúcar."],
    ["¿Venden carbón o leña?", "Sí, tenemos carbón, encendedores y algunos artículos de parrilla."],
    ["¿Cuentan con pilas o artículos de ferretería?", "Sí, tenemos pilas, bombitas y elementos básicos de ferretería."]
],

           "Métodos de pago": [
    ["¿Aceptan tarjeta de crédito?", "Sí, aceptamos tarjetas Visa, Mastercard, American Express y más."],
    ["¿Puedo pagar con débito?", "Sí, todas las tarjetas de débito están habilitadas."],
    ["¿Tienen posnet?", "Sí, contamos con terminal de cobro electrónico para tarjetas y billeteras."],
    ["¿Aceptan MercadoPago?", "Sí, podés abonar escaneando nuestro QR de MercadoPago."],
    ["¿Puedo pagar con Cuenta DNI?", "Sí, también recibimos pagos con Cuenta DNI."],
    ["¿Se puede pagar con transferencia?", "Sí, podés transferirnos desde tu homebanking y mostrar el comprobante."],
    ["¿Hacen descuento por pago en efectivo?", "Sí, ofrecemos un pequeño descuento si abonás en efectivo."],
    ["¿Puedo pagar con QR?", "Sí, todos nuestros medios digitales están disponibles mediante código QR."],
    ["¿Aceptan pagos con tarjeta alimentaria?", "Sí, aceptamos tarjeta Alimentar y otras similares según rubro habilitado."],
    ["¿Tienen cuotas sin interés?", "A veces ofrecemos promociones bancarias en cuotas sin interés."],
    ["¿Aceptan billeteras virtuales?", "Sí, podés pagar con MODO, Ualá, Naranja X y otras apps."],
    ["¿Puedo pagar online antes de retirar?", "Sí, podés abonar antes por transferencia o QR y retirar en el local."],
    ["¿Entregan factura por compras?", "Sí, emitimos factura A o B según lo que necesites."],
    ["¿Puedo pedir factura electrónica?", "Sí, todas las facturas pueden enviarse por correo electrónico."],
    ["¿Se puede pagar en dólares?", "En algunos casos, aceptamos dólares al tipo de cambio oficial del día."],
    ["¿Ofrecen promociones bancarias?", "Sí, trabajamos con promociones de bancos en fechas especiales."],
    ["¿Tienen promociones con tarjetas?", "Sí, a veces hay descuentos o reintegros con determinadas tarjetas."],
    ["¿Qué medios de pago NO aceptan?", "No trabajamos con cheques ni tarjetas no bancarias."],
    ["¿Aceptan pagos con criptomonedas?", "Por el momento no, pero lo estamos evaluando."],
    ["¿Se puede pagar al recibir en el domicilio?", "Sí, podés abonar en efectivo o con tarjeta al recibir."],
    ["¿El delivery tiene un costo adicional según el método de pago?", "No, el método de pago no modifica el precio del envío."],
    ["¿Hay un monto mínimo para pagar con tarjeta?", "Sí, el mínimo con tarjeta es de $2.000."],
    ["¿Puedo abonar con distintas formas de pago?", "Sí, podés combinar efectivo con tarjeta, por ejemplo."],
    ["¿Hay promociones si soy cliente frecuente?", "Sí, tenemos beneficios especiales para clientes habituales."],
    ["¿Aceptan pagos con QR de la app del banco?", "Sí, podés escanear el QR desde cualquier app bancaria."]
],

            "Horarios y envíos": [
    ["¿Cuál es el horario de atención?", "Estamos abiertos de lunes a sábado de 8 a 22 hs, y domingos de 9 a 14 hs."],
    ["¿Abren los feriados?", "Sí, algunos feriados abrimos medio día. Consultá antes de venir."],
    ["¿Hacen envíos a domicilio?", "Sí, realizamos entregas en la zona. Consultá disponibilidad según tu barrio."],
    ["¿Hay un mínimo de compra para envíos?", "Sí, el mínimo para delivery es de $3.000."],
    ["¿Qué zonas cubren con delivery?", "Entregamos en todo el radio céntrico y barrios cercanos al local."],
    ["¿Cuánto cuesta el envío?", "El costo del envío depende de la zona, desde $500 en adelante."],
    ["¿Cuánto demora el envío?", "Entre 30 y 60 minutos, según la ubicación y la demanda."],
    ["¿Puedo elegir el horario de entrega?", "Sí, podés indicarnos una franja horaria preferida."],
    ["¿Tienen envíos programados?", "Sí, podés agendar el envío para más tarde o el día siguiente."],
    ["¿Puedo hacer pedidos por WhatsApp?", "Sí, tomamos pedidos y coordinamos entregas por WhatsApp."],
    ["¿Puedo pasar a retirar por el local?", "Sí, podés hacer tu pedido y retirarlo sin demoras."],
    ["¿Entregan pedidos en el día?", "Sí, todos los pedidos del día se entregan el mismo día, salvo excepciones."],
    ["¿El delivery es propio o tercerizado?", "Tenemos repartidores propios para garantizar mejor atención."],
    ["¿Puedo hacer un pedido urgente?", "Sí, contamos con entregas prioritarias según disponibilidad."],
    ["¿Hay envíos gratuitos?", "Ofrecemos envío gratis en compras superiores a $10.000."],
    ["¿Hacen envíos los domingos?", "Sí, pero en horario reducido, de 9 a 14 hs."],
    ["¿Cómo sé si mi pedido está en camino?", "Te enviamos confirmación y seguimiento por WhatsApp o mail."],
    ["¿Qué pasa si no estoy cuando llega el pedido?", "Nos comunicamos con vos para reprogramar o dejarlo con alguien autorizado."],
    ["¿Se puede pagar al recibir?", "Sí, aceptamos efectivo, débito o QR en el momento de entrega."],
    ["¿Puedo cancelar un pedido?", "Sí, siempre que avises con antelación antes de salir a reparto."],
    ["¿Los productos llegan bien embalados?", "Sí, cuidamos cada pedido para que llegue en perfectas condiciones."],
    ["¿Entregan a oficinas o comercios?", "Sí, llevamos pedidos a cualquier punto dentro de la zona de reparto."],
    ["¿Cuántas veces por día hacen envíos?", "Hacemos entregas cada 2 horas, según demanda."],
    ["¿Puedo modificar mi pedido una vez enviado?", "Solo si aún no salió a reparto. Contactanos lo antes posible."],
    ["¿El repartidor puede ayudarme a subir el pedido?", "Sí, si lo necesitás y no implica dificultad, te damos una mano."]
],

           "Atención al cliente": [
    ["¿Tienen servicio de atención al cliente?", "Sí, podés comunicarte con nosotros por WhatsApp, teléfono o en el local."],
    ["¿Dónde puedo hacer un reclamo?", "Podés escribirnos por WhatsApp o acercarte al local con el ticket de compra."],
    ["¿Puedo devolver un producto?", "Sí, siempre que esté cerrado, en buen estado y con el comprobante de compra."],
    ["¿Cuánto tiempo tengo para hacer una devolución?", "Tenés hasta 48 horas desde la compra para realizar devoluciones."],
    ["¿Hacen cambios de productos vencidos?", "Sí, siempre que haya sido comprado en nuestro local y esté dentro del plazo."],
    ["¿Qué pasa si recibo un producto equivocado?", "Te lo cambiamos sin costo adicional en el menor tiempo posible."],
    ["¿Atienden reclamos por redes sociales?", "Sí, también respondemos mensajes en Instagram y Facebook."],
    ["¿Tienen número de teléfono directo?", "Sí, llamanos al número publicado en nuestro sitio o redes sociales."],
    ["¿Hay alguien encargado del servicio al cliente?", "Sí, contamos con un responsable de atención y resolución de reclamos."],
    ["¿Puedo pedir una factura corregida?", "Sí, presentá el comprobante original y corregimos los datos si es necesario."],
    ["¿Puedo hablar con un supervisor?", "Sí, si necesitás escalar un reclamo, te derivamos con un encargado."],
    ["¿Responden los mensajes fuera del horario comercial?", "Respondemos al día siguiente, apenas abrimos."],
    ["¿Puedo hacer un pedido personalizado?", "Sí, armamos pedidos especiales si lo solicitás con antelación."],
    ["¿Hacen envíos con comprobante?", "Sí, siempre enviamos el ticket o factura junto al pedido."],
    ["¿Los productos tienen garantía?", "Algunos productos sí. Consultá por productos eléctricos o especiales."],
    ["¿Puedo pedir que revisen un cobro?", "Sí, acercanos el comprobante y lo revisamos sin problema."],
    ["¿Qué pasa si no recibo todo lo que pedí?", "Lo resolvemos rápidamente, te reenviamos o reembolsamos lo faltante."],
    ["¿Atienden consultas en el local?", "Sí, nuestros empleados están capacitados para ayudarte en todo momento."],
    ["¿Puedo hacer un pedido con ayuda del personal?", "Sí, si no sabés qué llevar, te asesoramos con gusto."],
    ["¿Tienen atención preferencial para personas mayores?", "Sí, damos prioridad a adultos mayores y embarazadas."],
    ["¿Ofrecen productos recomendados según mi necesidad?", "Sí, podemos ayudarte a armar un pedido ajustado a lo que buscás."],
    ["¿Hay alguien que me pueda armar una lista semanal?", "Sí, si querés hacemos una lista recurrente de productos para vos."],
    ["¿Guardan historial de pedidos?", "Sí, si pedís por WhatsApp o con cuenta, podemos ver tu historial."],
    ["¿Se puede hacer una suscripción semanal?", "Estamos trabajando en un sistema de pedidos recurrentes. Consultanos."],
    ["¿Me pueden avisar si llega un producto que busco?", "Sí, te notificamos cuando esté disponible. Solo tenés que pedirlo."]
],

        }
    },
    "local_comercial": {
    "nombre": "Local Comercial",
    "descripcion": "Tiendas físicas que venden productos al público: indumentaria, tecnología, regalos, etc.",
    "categorias": {
        "Productos y servicios": [
    ["¿Tienen accesorios nuevos?", "Sí, renovamos stock todas las semanas con modelos y colores variados."],
    ["¿Reparan celulares?", "Sí, ofrecemos servicio técnico especializado para diferentes marcas y modelos."],
    ["¿Hacen composturas de ropa?", "Sí, realizamos arreglos simples como ruedos, cierres y ajustes de talle."],
    ["¿Tienen productos personalizados?", "Sí, personalizamos tazas, remeras, florería y más. Consultá por el tuyo."],
    ["¿Puedo encargar un ramo especial?", "Sí, armamos ramos a pedido para ocasiones especiales."],
    ["¿Venden estuches para celular?", "Sí, tenemos fundas y accesorios compatibles con la mayoría de modelos."],
    ["¿Tienen mochilas o carteras?", "Sí, contamos con una gran variedad de marroquinería."],
    ["¿Hacen combos o kits de regalo?", "Sí, podés armar un set personalizado con envoltorio incluido."],
    ["¿Ofrecen productos ecológicos?", "Sí, tenemos opciones sustentables como bolsas reutilizables y cosmética natural."],
    ["¿Venden ropa para niños?", "Sí, tenemos indumentaria infantil para todas las edades."],
    ["¿Tienen plantas o suculentas?", "Sí, ofrecemos plantas decorativas y regalos verdes."],
    ["¿Venden auriculares o parlantes?", "Sí, trabajamos con accesorios de audio para todos los dispositivos."],
    ["¿Hacen grabados personalizados?", "Sí, grabamos nombres o frases en productos seleccionados."],
    ["¿Tienen kits escolares?", "Sí, armamos combos completos para el colegio."],
    ["¿Puedo encargar productos por catálogo?", "Sí, podés elegir por catálogo digital y retirarlo o recibirlo."],
    ["¿Ofrecen juguetes didácticos?", "Sí, tenemos una línea educativa y recreativa para todas las edades."],
    ["¿Venden fundas para notebooks?", "Sí, contamos con fundas, bolsos y mochilas para notebooks."],
    ["¿Tienen productos de temporada?", "Sí, adaptamos el stock según cada época del año."],
    ["¿Hay productos en oferta hoy?", "Sí, siempre tenemos promociones activas. Consultá al momento de tu visita."],
    ["¿Tienen productos para cumpleaños?", "Sí, vendemos decoración, tarjetas y opciones para regalar."],
    ["¿Hacen bordados personalizados?", "Sí, ofrecemos bordado a pedido en prendas o artículos textiles."],
    ["¿Venden productos nacionales?", "Sí, trabajamos con emprendedores y marcas locales."],
    ["¿Puedo encargar talles grandes?", "Sí, tenemos disponibilidad por encargo en varios modelos."],
    ["¿Tienen velas aromáticas o ambientadores?", "Sí, ofrecemos productos de deco y fragancias para el hogar."],
    ["¿Hay productos para hombres y mujeres?", "Sí, tenemos variedad de opciones para todos los gustos."]
],

       "Formas de pago": [
    ["¿Aceptan tarjeta de crédito?", "Sí, aceptamos débito, crédito y billeteras virtuales."],
    ["¿Puedo pagar con QR?", "Sí, tenemos disponible el sistema de pago QR."],
    ["¿Aceptan MercadoPago?", "Sí, trabajamos con MercadoPago, tanto presencial como online."],
    ["¿Tienen cuotas sin interés?", "Sí, tenemos cuotas sin interés en días y bancos seleccionados."],
    ["¿Hacen descuento por pago en efectivo?", "Sí, ofrecemos un 10% de descuento abonando en efectivo."],
    ["¿Puedo pagar por transferencia?", "Sí, aceptamos transferencias bancarias con comprobante."],
    ["¿Aceptan Cuenta DNI?", "Sí, recibimos pagos a través de Cuenta DNI."],
    ["¿Tienen pago online?", "Sí, podés abonar desde nuestra tienda online con múltiples medios."],
    ["¿Puedo pagar cuando retiro?", "Sí, podés abonar al retirar en el local, con cualquier medio habilitado."],
    ["¿Aceptan tarjetas de todos los bancos?", "Sí, trabajamos con Visa, MasterCard, Naranja, y otras."],
    ["¿Tienen pago contra entrega?", "Sí, solo dentro de ciertas zonas. Consultá por tu ubicación."],
    ["¿Puedo pagar con tarjeta extranjera?", "Sí, aceptamos tarjetas internacionales en el local."],
    ["¿Aceptan pagos mixtos?", "Sí, podés combinar efectivo y tarjeta si lo necesitás."],
    ["¿Tienen promociones con bancos?", "Sí, ofrecemos beneficios con ciertos bancos y billeteras."],
    ["¿Puedo financiar una compra grande?", "Sí, consultá los planes disponibles para compras superiores a $50.000."],
    ["¿Aceptan tarjetas de planes sociales?", "Sí, recibimos tarjetas como Alimentar y similares."],
    ["¿Los pagos online son seguros?", "Sí, utilizamos plataformas con seguridad certificada."],
    ["¿Emitirán factura si pago con QR?", "Sí, se emite factura independientemente del medio de pago."],
    ["¿Hacen facturas A o B?", "Sí, emitimos ambos tipos de factura según necesidad del cliente."],
    ["¿Tienen posnet?", "Sí, contamos con terminal para pagos con tarjeta física o contactless."],
    ["¿Cobran recargo por tarjeta?", "No, el precio es el mismo en todos los medios de pago."],
    ["¿Puedo pagar por WhatsApp?", "Sí, te enviamos un link de pago seguro para abonar fácilmente."],
    ["¿Los precios son los mismos online y en el local?", "Sí, mantenemos coherencia en todos nuestros canales de venta."],
    ["¿Puedo reservar un producto y pagar después?", "Sí, podés hacer una seña y abonar el resto al retirar."],
    ["¿Aceptan pagos con Gift Cards?", "Sí, si son propias del local o emitidas por plataformas compatibles."]
],

       "Horarios y ubicación": [
    ["¿Dónde está ubicado el local?", "Estamos en una zona céntrica, consultá nuestro mapa en la web."],
    ["¿Cuál es la dirección exacta?", "Nos encontramos en Av. San Martín 1234, esquina Belgrano."],
    ["¿Tienen más de una sucursal?", "Sí, contamos con varias sucursales. Podés verlas en nuestra web."],
    ["¿Tienen estacionamiento?", "Sí, hay estacionamiento propio y público a pocos metros."],
    ["¿Cuáles son los horarios de atención?", "Abrimos de lunes a sábado de 10 a 20 hs."],
    ["¿Abren los domingos?", "Solo domingos especiales o en fechas festivas. Consultanos antes de venir."],
    ["¿Puedo pasar a retirar un pedido?", "Sí, podés retirar en el local una vez confirmada la compra."],
    ["¿Tienen atención continua?", "Sí, no cerramos al mediodía. Atendemos en horario corrido."],
    ["¿Abren en feriados?", "Algunos feriados estamos abiertos. Te recomendamos consultar previamente."],
    ["¿Tienen horario especial en verano?", "Sí, extendemos el horario en temporada alta. Lo informamos por redes."],
    ["¿Dónde puedo ver su ubicación?", "En nuestra web y redes tenés el mapa con dirección exacta."],
    ["¿Cómo llego en colectivo?", "Estamos a una cuadra de varias líneas. Consultá la más cercana según tu ubicación."],
    ["¿Puedo ir sin turno?", "Sí, no hace falta turno. Podés visitarnos cuando gustes dentro del horario."],
    ["¿A qué hora cierran?", "Cerramos a las 20 hs de lunes a sábado."],
    ["¿Están abiertos ahora?", "Consultá nuestro horario actualizado en Google Maps o redes sociales."],
    ["¿Hacen envíos si no puedo ir al local?", "Sí, podés comprar online y recibir en tu domicilio."],
    ["¿Atienden por WhatsApp fuera del horario?", "Sí, podés escribirnos y te responderemos a la brevedad."],
    ["¿Tienen delivery propio?", "Sí, tenemos envíos en zonas cercanas al local. Consultá por disponibilidad."],
    ["¿Puedo coordinar una visita fuera del horario?", "En casos especiales lo evaluamos. Escribinos para coordinar."],
    ["¿Hay alguna sucursal más cerca de mi zona?", "Podés consultarnos tu dirección y te indicamos la más cercana."],
    ["¿Tienen horario especial por eventos?", "Sí, extendemos el horario en fechas como Navidad o Día de la Madre."],
    ["¿Tienen atención telefónica?", "Sí, de lunes a sábado en nuestro horario comercial."],
    ["¿Dónde puedo encontrar su número?", "En el encabezado de nuestra web y perfil de redes sociales."],
    ["¿Cómo veo si están abiertos en Google?", "Buscanos como 'Chatboc Local' y verificá el horario ahí."],
    ["¿Puedo ir directo al local sin llamar?", "Sí, no hace falta avisar previamente."]
],

       "Políticas de cambios": [
    ["¿Se pueden cambiar los productos?", "Sí, con ticket y dentro de los 30 días de realizada la compra."],
    ["¿Qué necesito para hacer un cambio?", "Solo el ticket o comprobante de compra y el producto en buen estado."],
    ["¿Se puede cambiar sin ticket?", "No, es necesario el comprobante de compra para realizar el cambio."],
    ["¿Cuánto tiempo tengo para cambiar?", "Tenés hasta 30 días corridos desde la fecha de compra."],
    ["¿Puedo cambiar un regalo?", "Sí, siempre que esté sin uso y con comprobante o ticket de cambio."],
    ["¿Puedo cambiar si lo compré en oferta?", "Sí, aunque puede cambiar el valor. Consultanos antes de venir."],
    ["¿Se puede cambiar ropa usada?", "No, solo aceptamos productos sin uso y en perfectas condiciones."],
    ["¿Puedo cambiar productos de temporada pasada?", "Sí, dentro del plazo de 30 días y con ticket."],
    ["¿Cómo hago un cambio si compré online?", "Podés acercarte al local o coordinar el envío para realizar el cambio."],
    ["¿Puedo cambiar por otro producto?", "Sí, podés elegir otro producto del mismo valor o pagar la diferencia."],
    ["¿Puedo pedir devolución del dinero?", "Por el momento solo realizamos cambios o entregamos nota de crédito."],
    ["¿Puedo cambiar un producto dañado?", "Sí, si fue un defecto de fábrica. Revisaremos el caso."],
    ["¿Aceptan cambios en fechas especiales?", "Sí, extendemos plazos en fechas como Navidad o Día del Padre."],
    ["¿Puedo enviar a alguien más a hacer el cambio?", "Sí, con ticket y el producto. No hace falta que sea quien compró."],
    ["¿Dónde se hacen los cambios?", "Directamente en nuestro local o coordinando por WhatsApp si fue online."],
    ["¿Hay cambios los fines de semana?", "Sí, siempre dentro del horario comercial del local."],
    ["¿Cuánto demora el proceso de cambio?", "En el local es inmediato, si está en stock el producto deseado."],
    ["¿Hay productos que no tienen cambio?", "Sí, productos en liquidación final o usados no tienen cambio."],
    ["¿Puedo hacer un cambio sin envoltorio original?", "Depende del producto. Consultanos previamente."],
    ["¿Aceptan cambios de productos comprados en otras sucursales?", "Sí, si fue en alguna de nuestras tiendas oficiales."],
    ["¿Me dan un comprobante del cambio?", "Sí, entregamos constancia del nuevo producto o nota de crédito."],
    ["¿Qué pasa si no hay stock del producto que quiero?", "Podés elegir otro producto o esperar reposición."],
    ["¿El cambio tiene costo?", "No, siempre que sea dentro del plazo y condiciones acordadas."],
    ["¿Se puede cambiar un producto personalizado?", "No, los productos personalizados no tienen cambio."],
    ["¿Hasta qué hora hacen cambios?", "Durante todo nuestro horario comercial, de lunes a sábado."]
],

    }
}

}
