services:
  # 1. El Servidor Web Principal (Flask)
  - type: web
    name: chatboc-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_APP
        value: app.py

  # 2. El Cron Job (Automatización Semanal)
  - type: cron
    name: weekly-analytics-report
    env: python
    schedule: "0 0 * * 0" # Se ejecuta todos los domingos a las 00:00 UTC
    buildCommand: "./build.sh" # Usa las mismas dependencias
    startCommand: "flask generate-weekly-reports" # El comando que creamos en cli_commands.py
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_APP
        value: app.py
