"""Disposable PostgreSQL 18 restore drill. No Render/Neon credentials or customer data."""
import gzip
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import unittest
from uuid import uuid4
import psycopg2
from psycopg2 import sql
from scripts.recovery_archive import stage_export, restore_arguments, RecoveryArchiveError


class RecoveryPostgresTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        host = os.environ.get('RECOVERY_QA_PGHOST', '')
        if host not in ('127.0.0.1', 'postgres'):
            raise RuntimeError('Only the explicitly configured disposable QA service is allowed')
        cls.connection_args = {'host':host,'port':5432,'user':'recovery_qa',
                               'password':'recovery_qa_disposable_only','dbname':'postgres','connect_timeout':5}
        cls.environment = {key:value for key,value in os.environ.items() if not key.startswith('PG')}
        cls.environment.update(PGHOST=host,PGPORT='5432',PGUSER='recovery_qa',PGPASSWORD='recovery_qa_disposable_only',PGCONNECT_TIMEOUT='5')
        native = Path('/usr/lib/postgresql/18/bin/pg_restore')
        cls.tool = native if native.is_file() else Path(shutil.which('pg_restore') or '/missing-pg_restore')
        cls.dump_tool = cls.tool.with_name('pg_dump')
        cls.directory = tempfile.TemporaryDirectory(prefix='chatboc-archive-qa-')
        cls.root = Path(cls.directory.name)
        cls.source = 'recovery_source_' + uuid4().hex[:12]
        cls.admin = psycopg2.connect(**cls.connection_args); cls.admin.autocommit = True
        with cls.admin.cursor() as cursor:
            cursor.execute('SHOW server_version_num')
            if not 180000 <= int(cursor.fetchone()[0]) < 190000:
                raise RuntimeError('PostgreSQL 18 required for this drill')
            cursor.execute(sql.SQL('CREATE DATABASE {} TEMPLATE template0').format(sql.Identifier(cls.source)))
        with cls.connect(cls.source) as connection, connection.cursor() as cursor:
            cursor.execute('''CREATE TABLE tenant_profile(id integer PRIMARY KEY,name text NOT NULL);
                CREATE TABLE contact(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id integer NOT NULL REFERENCES tenant_profile(id),name text,
                    metadata jsonb,created_at timestamptz NOT NULL);
                CREATE TABLE case_record(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    contact_id bigint NOT NULL REFERENCES contact(id),status text NOT NULL,
                    CHECK(status IN ('new','closed')));
                CREATE INDEX contact_tenant_idx ON contact(tenant_id);
                CREATE TABLE change_log(case_id bigint NOT NULL,status text NOT NULL);
                CREATE FUNCTION record_case_change() RETURNS trigger LANGUAGE plpgsql AS $$
                    BEGIN INSERT INTO change_log VALUES(NEW.id,NEW.status); RETURN NEW; END $$;
                CREATE TRIGGER case_change AFTER INSERT ON case_record FOR EACH ROW EXECUTE FUNCTION record_case_change();
                INSERT INTO tenant_profile VALUES(1,'Municipio QA'),(2,'Empresa QA');
                INSERT INTO contact(tenant_id,name,metadata,created_at) VALUES
                    (1,'José QA', '{"consent":false,"note":"line 1\\nline 2"}', '2026-09-24T12:00:00Z'),
                    (2,NULL,'{"empty":null}', '2026-09-24T09:00:00-03:00');
                INSERT INTO case_record(contact_id,status) VALUES(1,'new'),(2,'closed');
                SELECT setval('contact_id_seq',41,true);''')
        with cls.connect(cls.source) as connection:
            large_object = connection.lobject(0, 'wb')
            try:
                large_object.write(b'QA binary payload\x00\x01')
            finally:
                large_object.close()
        cls.raw = cls.root / 'native-dump'
        dump = subprocess.run([str(cls.dump_tool), '--format=directory', '--no-owner', '--no-privileges',
                               '--dbname=' + cls.source, '--file=' + str(cls.raw)], env=cls.environment, capture_output=True)
        if dump.returncode:
            raise RuntimeError('Synthetic pg_dump failed')
        cls.archive = cls.root / 'export.dir.tar.gz'
        with tarfile.open(cls.archive,'w:gz') as bundle:
            bundle.add(cls.raw, arcname='export/'+cls.source)
        cls.digest = hashlib.sha256(cls.archive.read_bytes()).hexdigest()
        cls.prepared = cls.root / 'verified-dump'
        cls.proof = stage_export(cls.archive, cls.digest, cls.prepared, cls.source, cls.tool)

    @classmethod
    def tearDownClass(cls):
        with cls.admin.cursor() as cursor:
            cursor.execute(sql.SQL('DROP DATABASE {}').format(sql.Identifier(cls.source)))
        cls.admin.close(); cls.directory.cleanup()

    @classmethod
    def connect(cls, database):
        from contextlib import contextmanager
        @contextmanager
        def opened():
            connection=psycopg2.connect(**{**cls.connection_args,'dbname':database})
            try:
                with connection: yield connection
            finally: connection.close()
        return opened()

    def setUp(self):
        self.target = 'chatboc_recovery_20260925_' + uuid4().hex[:12]
        with self.admin.cursor() as cursor:
            cursor.execute(sql.SQL('CREATE DATABASE {} TEMPLATE template0').format(sql.Identifier(self.target)))

    def tearDown(self):
        with self.admin.cursor() as cursor:
            cursor.execute(sql.SQL('DROP DATABASE {}').format(sql.Identifier(self.target)))

    def restore(self, dump=None):
        with self.connect(self.target) as connection, connection.cursor() as cursor:
            cursor.execute("SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public'")
            self.assertEqual(cursor.fetchone()[0],0,'Synthetic restore target must be empty')
        return subprocess.run(restore_arguments(self.tool,dump or self.prepared,self.target),
                              env=self.environment,capture_output=True,timeout=60)

    def fingerprint(self, database):
        result={}
        with self.connect(database) as connection, connection.cursor() as cursor:
            cursor.execute("SET TIME ZONE 'UTC'")
            for table in ('tenant_profile','contact','case_record','change_log'):
                cursor.execute(sql.SQL("SELECT count(*),encode(sha256(convert_to(coalesce(string_agg(to_jsonb(t)::text,chr(10) ORDER BY to_jsonb(t)::text),''),'UTF8')),'hex') FROM {} t").format(sql.Identifier(table)))
                result[table]=cursor.fetchone()
        return result

    def test_01_native_archive_is_structurally_verified_not_restored(self):
        self.assertTrue(self.proof['archive_validated']); self.assertFalse(self.proof['restore_executed'])
        self.assertEqual(self.proof['object_counts']['TABLE'],4)
        self.assertEqual(self.proof['object_counts']['TABLE DATA'],4)
        self.assertFalse(self.proof['cutover_authorized'])

    def test_02_real_restore_preserves_all_rows_including_nulls_and_json(self):
        before=self.fingerprint(self.source)
        self.assertEqual(self.restore().returncode,0)
        self.assertEqual(self.fingerprint(self.target),before)
        self.assertEqual(self.fingerprint(self.source),before)

    def test_03_sequence_state_and_next_identity_are_preserved(self):
        self.assertEqual(self.restore().returncode,0)
        states=[]
        for database in (self.source,self.target):
            with self.connect(database) as connection, connection.cursor() as cursor:
                cursor.execute('SELECT last_value,is_called FROM contact_id_seq'); states.append(cursor.fetchone())
        self.assertEqual(states,[(41,True),(41,True)])
        with self.connect(self.target) as connection, connection.cursor() as cursor:
            cursor.execute("INSERT INTO contact(tenant_id,created_at) VALUES(1,now()) RETURNING id")
            self.assertEqual(cursor.fetchone()[0],42)

    def test_04_constraints_indexes_and_trigger_are_restored(self):
        self.assertEqual(self.restore().returncode,0)
        with self.connect(self.target) as connection, connection.cursor() as cursor:
            cursor.execute("SELECT count(*) FROM pg_indexes WHERE schemaname='public' AND indexname='contact_tenant_idx'")
            self.assertEqual(cursor.fetchone()[0],1)
            cursor.execute("INSERT INTO case_record(contact_id,status) VALUES(1,'new') RETURNING id")
            case_id=cursor.fetchone()[0]
            cursor.execute('SELECT count(*) FROM change_log WHERE case_id=%s',(case_id,))
            self.assertEqual(cursor.fetchone()[0],1)
        with self.assertRaises(psycopg2.IntegrityError):
            with self.connect(self.target) as connection, connection.cursor() as cursor:
                cursor.execute("INSERT INTO case_record(contact_id,status) VALUES(9999,'new')")

    def test_05_nonempty_destination_is_not_overwritten(self):
        with self.connect(self.target) as connection, connection.cursor() as cursor:
            cursor.execute('CREATE TABLE must_keep(id integer);INSERT INTO must_keep VALUES(9)')
        with self.assertRaises(AssertionError): self.restore()
        with self.connect(self.target) as connection, connection.cursor() as cursor:
            cursor.execute('SELECT id FROM must_keep'); self.assertEqual(cursor.fetchall(),[(9,)])

    def test_06_failed_copy_rolls_back_the_entire_restore(self):
        damaged=self.root/('damaged-'+uuid4().hex[:8]); shutil.copytree(self.prepared,damaged)
        listing=subprocess.check_output([str(self.tool),'--list',str(damaged)],text=True,env=self.environment)
        entry=re.search(r'^(\d+);.* TABLE DATA public tenant_profile ',listing,re.M)[1]
        file=next(path for path in damaged.iterdir() if path.name in (entry+'.dat',entry+'.dat.gz'))
        body=gzip.decompress(file.read_bytes()) if file.suffix=='.gz' else file.read_bytes()
        body=b'not-an-integer'+body[body.index(b'\t'):]
        file.write_bytes(gzip.compress(body) if file.suffix=='.gz' else body)
        result=self.restore(damaged)
        self.assertNotEqual(result.returncode,0)
        with self.connect(self.target) as connection,connection.cursor() as cursor:
            cursor.execute("SELECT count(*) FROM pg_tables WHERE schemaname='public'")
            self.assertEqual(cursor.fetchone()[0],0)
        shutil.rmtree(damaged)

    def test_07_table_of_contents_is_not_accepted_without_data_files(self):
        archive=self.root/('missing-'+uuid4().hex[:8]+'.tar.gz')
        with tarfile.open(archive,'w:gz') as bundle:
            bundle.add(self.raw/'toc.dat',arcname='db/toc.dat')
        with self.assertRaises(RecoveryArchiveError):
            stage_export(archive,hashlib.sha256(archive.read_bytes()).hexdigest(),
                         self.root/('rejected-'+uuid4().hex[:8]),self.source,self.tool)

    def test_08_large_object_payload_survives_restore(self):
        self.assertEqual(self.restore().returncode,0)
        snapshots=[]
        for database in (self.source,self.target):
            with self.connect(database) as connection,connection.cursor() as cursor:
                cursor.execute("SELECT oid,encode(sha256(lo_get(oid)),'hex') FROM pg_largeobject_metadata ORDER BY oid")
                snapshots.append(cursor.fetchall())
        self.assertEqual(snapshots[0],snapshots[1]);self.assertEqual(len(snapshots[0]),1)

if __name__=='__main__':
    destination=Path(os.environ.get('RECOVERY_QA_EVIDENCE','recovery-evidence'));destination.mkdir(parents=True,exist_ok=True)
    with (destination/'postgres-restore-tests.log').open('w',encoding='utf-8') as stream:
        result=unittest.TextTestRunner(stream=stream,verbosity=2).run(unittest.defaultTestLoader.loadTestsFromTestCase(RecoveryPostgresTests))
    report={'tests':result.testsRun,'errors':len(result.errors),'failures':len(result.failures),'success':result.wasSuccessful(),'real_pg_dump_restore':True,'synthetic_database':True,'customer_restore':False,'cloud_connections':False}
    (destination/'postgres-restore-results.json').write_text(json.dumps(report),encoding='utf-8')
    print(json.dumps(report));raise SystemExit(0 if result.wasSuccessful() else 1)
