import {chromium, expect} from '@playwright/test';
import {createServer} from 'vite';
import {mkdir, readFile, writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const ui = JSON.parse(await readFile('tests/fixtures/template-workspace-ui.json', 'utf8'));
const server = await createServer({cacheDir: '.vercel/template-library-cache', server:{host:'127.0.0.1',port:0},logLevel:'error'});
let browser;
const results = [];
try {
  await server.listen(); const origin = `http://127.0.0.1:${server.httpServer.address().port}`;
  browser = await chromium.launch(process.platform==='win32'?{channel:'chrome',headless:true}:{headless:true});
  await mkdir('.vercel/template-library-evidence', {recursive:true});
  const context = await browser.newContext({viewport:{width:1440,height:1000}, reducedMotion:'reduce'});
  const login = await context.request.post(origin+'/auth/login', {data:{email:process.env.CHATBOC_ACCEPTANCE_EMAIL,password:process.env.CHATBOC_ACCEPTANCE_PASSWORD}});
  assert.equal(login.status(),200); assert.ok((await login.json()).token);
  const catalogPath = '/api/admin/whatsapp/template-packs?tenant_slug=acceptance-a';
  const source = await context.request.get(origin+catalogPath); assert.equal(source.status(),200);
  const actual = await source.json(); assert.deepEqual(actual.frontend_contract.workspace_ui, ui);
  const pack = actual.packs.find(item => item.vertical==='municipio'); assert.equal(pack.templates.length,5);
  const page = await context.newPage(); const errors=[]; const writes=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',request=>{if(request.method()==='POST'&&new URL(request.url()).pathname.includes('/template-packs/'))writes.push(request);});
  await page.route('**/*',route=>['127.0.0.1','localhost','::1'].includes(new URL(route.request().url()).hostname)?route.continue():route.abort('blockedbyclient'));
  await page.goto(origin+'/tests/e2e/fixtures/template-workspace.html?tenant_slug=acceptance-a');
  const search = page.getByRole('searchbox',{name:ui.search_label}); await expect(search).toBeVisible();
  await search.fill('PAGO'); await expect(page.getByRole('article')).toHaveCount(1);
  await page.getByRole('button',{name:ui.create,exact:true}).click();
  await expect(page.getByRole('alertdialog')).toContainText(ui.confirm_description);
  await page.getByRole('button',{name:ui.cancel,exact:true}).click(); assert.equal(writes.length,0);
  await page.getByRole('button',{name:ui.create,exact:true}).click();
  await page.getByRole('button',{name:ui.confirm_action,exact:true}).click();
  await expect(page.getByRole('button',{name:ui.created,exact:true})).toBeDisabled(); assert.equal(writes.length,1);
  const persistedResponse = await context.request.get(origin+catalogPath); const persisted = await persistedResponse.json();
  assert.ok(persisted.packs.find(item=>item.vertical==='municipio').templates.every(item=>item.materialized===true&&item.lifecycle.production_send_allowed===false));
  await page.reload(); await expect(page.getByRole('button',{name:ui.created,exact:true})).toBeDisabled();
  await expect(page.getByRole('article')).toHaveCount(5); assert.equal(writes.length,1);
  for(const [width,dark] of [[1440,false],[820,false],[390,true],[320,false]]) {
    await page.setViewportSize({width,height:1000});
    await page.evaluate(dark=>document.documentElement.classList.toggle('dark',dark),dark);
    await page.getByRole('combobox',{name:ui.state_label}).selectOption('approved');
    await expect(page.getByText(ui.no_results,{exact:true})).toBeVisible();
    const readFinished = page.waitForResponse(response=>new URL(response.url()).pathname==='/api/admin/whatsapp/template-packs'&&response.request().method()==='GET');
    await page.getByRole('button',{name:ui.refresh,exact:true}).click();
    assert.equal((await readFinished).status(),200);
    await expect(page.getByRole('button',{name:ui.refresh,exact:true})).toBeEnabled();
    await expect(page.getByRole('combobox',{name:ui.state_label})).toHaveValue('approved');
    await expect(page.getByText(ui.no_results,{exact:true})).toBeVisible();
    await page.getByRole('button',{name:ui.clear_filters,exact:true}).click();
    await expect(page.getByRole('article')).toHaveCount(5);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
    await page.screenshot({path:`.vercel/template-library-evidence/library-${width}.png`,fullPage:true});
    results.push({width,dark,noHorizontalOverflow:true,zeroFilterPreserved:true,refreshResponseVerified:true,localDraftsPersisted:true});
  }
  assert.deepEqual(errors,[]); assert.equal(writes.length,1);
  const headers = await writes[0].allHeaders(); assert.ok(headers['idempotency-key']);
  const second = await browser.newContext();
  const secondLogin=await second.request.post(origin+'/auth/login',{data:{email:process.env.CHATBOC_ACCEPTANCE_SECOND_EMAIL,password:process.env.CHATBOC_ACCEPTANCE_PASSWORD}});
  assert.equal(secondLogin.status(),200); const read=await second.request.get(origin+catalogPath);
  assert.equal(read.status(),200); assert.ok((await read.json()).packs.find(item=>item.vertical==='municipio').templates.every(item=>item.materialized===true));
  await second.close(); await context.close();
  const report={fullFlaskApp:true,actualComponent:true,mockedApiResponses:false,syntheticAccountsAndDatabase:true,providerCalls:false,confirmedDraftWrites:1,results};
  await writeFile('.vercel/template-library-evidence/results.json',JSON.stringify(report,null,2)); console.log(JSON.stringify(report));
} finally {await browser?.close();await server.close();}
