"""Reestructura relacion de comentarios de tickets

Revision ID: 02dde0c0d10f
Revises: 1be7ae934da3
Create Date: 2025-06-07 23:10:55.466312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02dde0c0d10f'
down_revision = '1be7ae934da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pyme_pedido')
    with op.batch_alter_table('ticket_comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pyme_ticket_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('municipio_ticket_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'municipio_ticket', ['municipio_ticket_id'], ['id'])
        batch_op.create_foreign_key(None, 'pyme_ticket', ['pyme_ticket_id'], ['id'])
        batch_op.drop_column('email')
        batch_op.drop_column('dni')
        batch_op.drop_column('estado_cliente')
        batch_op.drop_column('telefono')
        batch_op.drop_column('tipo_ticket')
        batch_op.drop_column('ticket_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('tipo_ticket', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('estado_cliente', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('dni', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('municipio_ticket_id')
        batch_op.drop_column('pyme_ticket_id')

    op.create_table('pyme_pedido',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('nro_pedido', sa.VARCHAR(length=50), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=30), nullable=True),
    sa.Column('detalles', sa.TEXT(), nullable=True),
    sa.Column('monto_total', sa.FLOAT(), nullable=True),
    sa.Column('fecha', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_pedido')
    )
    # ### end Alembic commands ###
