"""add canal_ingreso to municipio_ticket

Revision ID: 063947b34b71
Revises: 494b2f77c12c
Create Date: 2025-08-06 01:03:13.449864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063947b34b71'
down_revision = '494b2f77c12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distrito', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.drop_column('distrito')

    # ### end Alembic commands ###
