"""Agrego campos nombre_empresa y rubro_id a User

Revision ID: 142113b0fb95
Revises: 591156f7e2ee
Create Date: 2025-05-19 16:56:36.081485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142113b0fb95'
down_revision = '591156f7e2ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_empresa', sa.String(length=150), nullable=True))
        batch_op.create_foreign_key('fk_user_rubro_id', 'rubro', ['rubro_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('nombre_empresa')

    # ### end Alembic commands ###
