"""add rubro_id to qa

Revision ID: 180ecd5b2304
Revises: 
Create Date: 2025-05-14 10:21:12.088857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180ecd5b2304'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_qa_rubro_id', 'rubro', ['rubro_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
         batch_op.create_foreign_key('fk_qa_rubro_id', 'rubro', ['rubro_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
