"""Migración limpia post-borrado

Revision ID: 1a8fc44611b5
Revises: 676de9de1571
Create Date: 2025-07-06 12:57:03.953182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8fc44611b5'
down_revision = '676de9de1571'
branch_labels = None
depends_on = None


def upgrade():
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_url', sa.VARCHAR(length=255), nullable=True))

    op.create_table('_alembic_tmp_municipio_ticket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pregunta', sa.TEXT(), nullable=False),
    sa.Column('asunto', sa.VARCHAR(length=200), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=30), nullable=True),
    sa.Column('anon_id', sa.VARCHAR(length=80), nullable=True),
    sa.Column('ultima_actividad', sa.DATETIME(), nullable=True),
    sa.Column('nro_ticket', sa.INTEGER(), nullable=False),
    sa.Column('detalles', sa.TEXT(), nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=255), nullable=True),
    sa.Column('latitud', sa.FLOAT(), nullable=True),
    sa.Column('longitud', sa.FLOAT(), nullable=True),
    sa.Column('fecha', sa.DATETIME(), nullable=True),
    sa.Column('municipio_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_ticket')
    )
    # ### end Alembic commands ###
