"""Crear tabla para sesiones del servidor

Revision ID: 1be7ae934da3
Revises: f8d892575a95
Create Date: 2025-06-07 22:46:24.672844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be7ae934da3'
down_revision = 'f8d892575a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pyme_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nro_pedido', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_pedido')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pyme_pedido')
    # ### end Alembic commands ###
