"""Add dispatch and notification configuration to TenantProfile

Revision ID: 20300121_add_dispatch_notification_config
Revises: 20300120_add_analytics_event
Create Date: 2030-01-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20300121'
down_revision = '20300120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('tenant_profile')]

    if 'dispatch_email' not in columns:
        op.add_column('tenant_profile', sa.Column('dispatch_email', sa.String(length=255), nullable=True))
    if 'dispatch_phone' not in columns:
        op.add_column('tenant_profile', sa.Column('dispatch_phone', sa.String(length=50), nullable=True))
    if 'send_buyer_email' not in columns:
        op.add_column('tenant_profile', sa.Column('send_buyer_email', sa.Boolean(), server_default='true', nullable=False))
    if 'send_dispatch_email' not in columns:
        op.add_column('tenant_profile', sa.Column('send_dispatch_email', sa.Boolean(), server_default='true', nullable=False))
    if 'send_dispatch_whatsapp' not in columns:
        op.add_column('tenant_profile', sa.Column('send_dispatch_whatsapp', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_profile', 'send_dispatch_whatsapp')
    op.drop_column('tenant_profile', 'send_dispatch_email')
    op.drop_column('tenant_profile', 'send_buyer_email')
    op.drop_column('tenant_profile', 'dispatch_phone')
    op.drop_column('tenant_profile', 'dispatch_email')
    # ### end Alembic commands ###
