"""Add fecha_vigencia to catalogo_item

Revision ID: 20300114_add_fecha_vigencia_to_catalogo_item
Revises: 20300113
Create Date: 2026-01-30 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20300114'
down_revision = '20300113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists first to be safe (though alembic usually handles this, idempotent is better)
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('catalogo_item')]

    if 'fecha_vigencia' not in columns:
        op.add_column('catalogo_item', sa.Column('fecha_vigencia', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogo_item', 'fecha_vigencia')
    # ### end Alembic commands ###
