"""Add dispatch fields to tenant_profile

Revision ID: 20300115_add_dispatch_fields_to_tenant
Revises: 20300114_add_fecha_vigencia_to_catalogo_item
Create Date: 2026-01-30 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20300115_add_dispatch_fields_to_tenant'
down_revision = '20300114_add_fecha_vigencia_to_catalogo_item'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    columns = [col['name'] for col in inspector.get_columns('tenant_profile')]

    if 'dispatch_email' not in columns:
        op.add_column('tenant_profile', sa.Column('dispatch_email', sa.String(length=255), nullable=True))
    if 'dispatch_phone' not in columns:
        op.add_column('tenant_profile', sa.Column('dispatch_phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_profile', 'dispatch_phone')
    op.drop_column('tenant_profile', 'dispatch_email')
    # ### end Alembic commands ###
