"""add_wine_fields_to_catalogo_item

Revision ID: 20300126_add_wine_fields
Revises: 20300125_add_tenant_widget_config
Create Date: 2030-01-26 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20300126_add_wine_fields'
down_revision = '20300125_add_tenant_widget_config'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('varietal', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('anada', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('presentacion', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_item', schema=None) as batch_op:
        batch_op.drop_column('presentacion')
        batch_op.drop_column('anada')
        batch_op.drop_column('varietal')

    # ### end Alembic commands ###
