"""Add nuevo campo en MunicipioTicket

Revision ID: 2cd1bd3fa7dd
Revises: ce8254522e14
Create Date: 2025-08-27 11:47:52.667910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd1bd3fa7dd'
down_revision = 'ce8254522e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dni_vecino', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.drop_column('dni_vecino')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), nullable=True),
    sa.Column('rol', sa.VARCHAR(length=30), nullable=True),
    sa.Column('tipo_chat', sa.VARCHAR(length=20), nullable=True),
    sa.Column('pyme_id', sa.INTEGER(), nullable=True),
    sa.Column('municipio_id', sa.INTEGER(), nullable=True),
    sa.Column('nombre_empresa', sa.VARCHAR(length=150), nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=200), nullable=True),
    sa.Column('ciudad', sa.VARCHAR(length=100), nullable=True),
    sa.Column('provincia', sa.VARCHAR(length=100), nullable=True),
    sa.Column('pais', sa.VARCHAR(length=100), nullable=True),
    sa.Column('latitud', sa.FLOAT(), nullable=True),
    sa.Column('longitud', sa.FLOAT(), nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=20), nullable=True),
    sa.Column('link_web', sa.VARCHAR(length=255), nullable=True),
    sa.Column('logo_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('color_primario', sa.VARCHAR(length=20), nullable=True),
    sa.Column('color_secundario', sa.VARCHAR(length=20), nullable=True),
    sa.Column('badge_tipo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('acepto_terminos', sa.BOOLEAN(), nullable=True),
    sa.Column('fecha_aceptacion_terminos', sa.DATETIME(), nullable=True),
    sa.Column('acepta_marketing', sa.BOOLEAN(), nullable=True),
    sa.Column('fecha_aceptacion_marketing', sa.DATETIME(), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ticket_categorias', sa.VARCHAR(length=255), nullable=True),
    sa.Column('horario', sa.VARCHAR(length=100), nullable=True),
    sa.Column('plan', sa.VARCHAR(length=20), nullable=True),
    sa.Column('preguntas_usadas', sa.INTEGER(), nullable=True),
    sa.Column('limite_preguntas', sa.INTEGER(), nullable=True),
    sa.Column('last_reset', sa.DATETIME(), nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), nullable=True),
    sa.Column('rubro_id', sa.INTEGER(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.Column('prefers_audio', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
