"""add anon_id to tickets

Revision ID: 2ff53327300b
Revises: 8a36a966bd63
Create Date: 2025-06-14 02:49:12.525771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff53327300b'
down_revision = '8a36a966bd63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anon_id', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_municipio_ticket_anon_id'), ['anon_id'], unique=False)

    with op.batch_alter_table('pyme_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anon_id', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_pyme_ticket_anon_id'), ['anon_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyme_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pyme_ticket_anon_id'))
        batch_op.drop_column('anon_id')

    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_municipio_ticket_anon_id'))
        batch_op.drop_column('anon_id')

    # ### end Alembic commands ###
