"""Agregar campos acepto_terminos y fecha_aceptacion_terminos a User

Revision ID: 3550466abf47
Revises: e1b12ba1d6c6
Create Date: 2025-06-03 01:27:37.783487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3550466abf47'
down_revision = 'e1b12ba1d6c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acepto_terminos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_aceptacion_terminos', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fecha_aceptacion_terminos')
        batch_op.drop_column('acepto_terminos')

    # ### end Alembic commands ###
