"""init full reset

Revision ID: 36e6d0ec0e51
Revises: 
Create Date: 2025-06-24 01:05:45.759031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '36e6d0ec0e51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.String(length=500), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipio_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('anon_id', sa.String(length=80), nullable=True),
    sa.Column('ultima_actividad', sa.DateTime(), nullable=True),
    sa.Column('nro_ticket', sa.Integer(), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('archivo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_ticket')
    )
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_municipio_ticket_anon_id'), ['anon_id'], unique=False)

    op.create_table('rubro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['padre_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('ticket_satisfaccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pyme_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('anon_id', sa.String(length=80), nullable=True),
    sa.Column('nro_ticket', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('archivo_url', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('estado_cliente', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_ticket')
    )
    with op.batch_alter_table('pyme_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pyme_ticket_anon_id'), ['anon_id'], unique=False)

    op.create_table('qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sugerencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('rol', sa.String(length=30), nullable=True),
    sa.Column('pyme_id', sa.Integer(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('nombre_empresa', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('link_web', sa.String(length=255), nullable=True),
    sa.Column('acepto_terminos', sa.Boolean(), nullable=True),
    sa.Column('fecha_aceptacion_terminos', sa.DateTime(), nullable=True),
    sa.Column('acepta_marketing', sa.Boolean(), nullable=True),
    sa.Column('fecha_aceptacion_marketing', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('ticket_categorias', sa.String(length=255), nullable=True),
    sa.Column('horario', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('preguntas_usadas', sa.Integer(), nullable=True),
    sa.Column('limite_preguntas', sa.Integer(), nullable=True),
    sa.Column('last_reset', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('archivo_adjunto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('tamano', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('pyme_ticket_id', sa.Integer(), nullable=True),
    sa.Column('municipio_ticket_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_ticket_id'], ['municipio_ticket.id'], ),
    sa.ForeignKeyConstraint(['pyme_ticket_id'], ['pyme_ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogo_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.String(length=1024), nullable=True),
    sa.Column('precio', sa.String(length=50), nullable=True),
    sa.Column('embedding_vector', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogo_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=1024), nullable=True),
    sa.Column('precio', sa.String(length=50), nullable=True),
    sa.Column('cantidad', sa.String(length=50), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('embedding', sa.PickleType(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogo_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogo_item_marca'), ['marca'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalogo_item_sku'), ['sku'], unique=False)

    op.create_table('conversacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('fuente', sa.String(length=50), nullable=False),
    sa.Column('rubro', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversacion', schema=None) as batch_op:
        batch_op.create_index('ix_conversacion_session_id', ['session_id'], unique=False)

    op.create_table('pyme_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nro_pedido', sa.String(length=50), nullable=False),
    sa.Column('asunto', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('nombre_cliente', sa.String(length=100), nullable=True),
    sa.Column('email_cliente', sa.String(length=100), nullable=True),
    sa.Column('telefono_cliente', sa.String(length=50), nullable=True),
    sa.Column('rubro', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_pedido')
    )
    op.create_table('recordatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.Column('enviado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sitio_web_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('datos_json', sa.Text(), nullable=False),
    sa.Column('fecha_scraping', sa.DateTime(), nullable=True),
    sa.Column('actualizado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pyme_ticket_id', sa.Integer(), nullable=True),
    sa.Column('municipio_ticket_id', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anon_id', sa.String(length=80), nullable=True),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_ticket_id'], ['municipio_ticket.id'], ),
    sa.ForeignKeyConstraint(['pyme_ticket_id'], ['pyme_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_comentario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_comentario_anon_id'), ['anon_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comentario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_comentario_anon_id'))

    op.drop_table('ticket_comentario')
    op.drop_table('sitio_web_info')
    op.drop_table('recordatorio')
    op.drop_table('pyme_pedido')
    with op.batch_alter_table('conversacion', schema=None) as batch_op:
        batch_op.drop_index('ix_conversacion_session_id')

    op.drop_table('conversacion')
    with op.batch_alter_table('catalogo_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogo_item_sku'))
        batch_op.drop_index(batch_op.f('ix_catalogo_item_marca'))

    op.drop_table('catalogo_item')
    op.drop_table('catalogo_embedding')
    op.drop_table('archivo_adjunto')
    op.drop_table('user')
    op.drop_table('sugerencia')
    op.drop_table('qa')
    with op.batch_alter_table('pyme_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pyme_ticket_anon_id'))

    op.drop_table('pyme_ticket')
    op.drop_table('ticket_satisfaccion')
    op.drop_table('rubro')
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_municipio_ticket_anon_id'))

    op.drop_table('municipio_ticket')
    op.drop_table('logs')
    # ### end Alembic commands ###
