"""add_chat_session_context_table

Revision ID: 3d9a0f8b2c5e
Revises: ee3694e2e48a
Create Date: 2024-07-26 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9a0f8b2c5e'
down_revision = 'ee3694e2e48a' # Point to the latest existing one, or adjust if there are branches
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session_context',
    sa.Column('chat_session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anon_id', sa.String(length=80), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('chat_session_id')
    )
    with op.batch_alter_table('chat_session_context', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_session_context_anon_id'), ['anon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_session_context_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session_context', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_session_context_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_session_context_anon_id'))

    op.drop_table('chat_session_context')
    # ### end Alembic commands ###
