"""Agregar limite_preguntas correctamente a User

Revision ID: 44284b9336c7
Revises: 180ecd5b2304
Create Date: 2025-05-17 10:01:08.157934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44284b9336c7'
down_revision = '180ecd5b2304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('padre_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'rubro', ['padre_id'], ['id'])
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limite_preguntas', sa.Integer(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.drop_constraint('fk_qa_rubro_id', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_qa_rubro_id', 'rubro', ['rubro_id'], ['id'])
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('limite_preguntas')

    with op.batch_alter_table('rubro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'rubro', ['parent_id'], ['id'])
        batch_op.drop_column('padre_id')

    # ### end Alembic commands ###
