"""Add new fields to MunicipioTicket

Revision ID: 494b2f77c12c
Revises: c81ab00745d9
Create Date: 2025-08-05 04:54:02.653524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494b2f77c12c'
down_revision = 'c81ab00745d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canal_ingreso', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contacto_seguimiento', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nombre_display_whatsapp', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('url_avatar_whatsapp', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.drop_column('url_avatar_whatsapp')
        batch_op.drop_column('nombre_display_whatsapp')
        batch_op.drop_column('contacto_seguimiento')
        batch_op.drop_column('canal_ingreso')

    # ### end Alembic commands ###
