"""agrego tabla ArchivoAdjunto

Revision ID: 54a210dac5c9
Revises: 87bc12504f02
Create Date: 2025-06-23 07:28:18.566940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a210dac5c9'
down_revision = '87bc12504f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivo_adjunto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('tamano', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('pyme_ticket_id', sa.Integer(), nullable=True),
    sa.Column('municipio_ticket_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_ticket_id'], ['municipio_ticket.id'], ),
    sa.ForeignKeyConstraint(['pyme_ticket_id'], ['pyme_ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archivo_adjunto')
    # ### end Alembic commands ###
