"""Agrego campo categoria a QA

Revision ID: 591156f7e2ee
Revises: 180ecd5b2304
Create Date: 2025-05-17 14:46:47.085908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591156f7e2ee'
down_revision = '180ecd5b2304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_rubro')
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qa', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    op.create_table('_alembic_tmp_rubro',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('clave', sa.VARCHAR(length=50), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('padre_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['padre_id'], ['rubro.id'], name='fk_rubro_padre_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    # ### end Alembic commands ###
