"""agrego tabla ArchivoAdjunto

Revision ID: 5d7f9ba79a52
Revises: 54a210dac5c9
Create Date: 2025-06-23 20:18:12.046667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7f9ba79a52'
down_revision = '54a210dac5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pyme_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('municipio_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('municipio_id')
        batch_op.drop_column('pyme_id')

    # ### end Alembic commands ###
