"""Hacer campos de PymePedido opcionales para migración

Revision ID: 5f78969571e8
Revises: a2c074e6c0d1
Create Date: 2025-06-10 22:36:59.120474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f78969571e8'
down_revision = 'a2c074e6c0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyme_pedido', schema=None) as batch_op:
        batch_op.alter_column('asunto',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('rubro',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyme_pedido', schema=None) as batch_op:
        batch_op.alter_column('rubro',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('asunto',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
