"""Agrego columna pyme_id a Conversacion

Revision ID: 60e14df94985
Revises: edb21c2c3bdd
Create Date: 2025-07-28 20:24:00.995799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e14df94985'
down_revision = 'edb21c2c3bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pyme_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_conversacion_pyme_id', 'user', ['pyme_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pyme_id')

    # ### end Alembic commands ###
