"""add catalog upload extended fields

Revision ID: 63d5d1f8a654
Revises: 20300124
Create Date: 2026-02-04 01:38:44.912705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d5d1f8a654'
down_revision = '20300124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
