"""Agregar campo cantidad a CatalogoEmbedding

Revision ID: 657c51097011
Revises: 25fc7af050e5
Create Date: 2025-05-27 20:45:11.964345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657c51097011'
down_revision = '25fc7af050e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_embedding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cantidad', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_embedding', schema=None) as batch_op:
        batch_op.drop_column('cantidad')

    # ### end Alembic commands ###
