"""add ticket_comentario table

Revision ID: 66d26c5f27d5
Revises: 6b25c443ab3f
Create Date: 2025-06-05 23:45:26.294213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d26c5f27d5'
down_revision = '6b25c443ab3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitio_web_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('datos_json', sa.Text(), nullable=False),
    sa.Column('fecha_scraping', sa.DateTime(), nullable=True),
    sa.Column('actualizado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitio_web_info')
    # ### end Alembic commands ###
