"""add ticket_comentario table

Revision ID: 6b25c443ab3f
Revises: 7c5fd1990259
Create Date: 2025-06-04 21:30:53.507480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b25c443ab3f'
down_revision = '7c5fd1990259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comentario', schema=None) as batch_op:
        batch_op.drop_column('es_admin')

    # ### end Alembic commands ###
