"""add education and analytics tables

Revision ID: 71c9a10fb7cb
Revises: de53397ead1d
Create Date: 2026-04-25 23:44:20.309424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c9a10fb7cb'
down_revision = 'de53397ead1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
