"""Add pyme_id to PymePedido and remove rubro

Revision ID: 71dfd553cd5b
Revises: d6709e14f414
Create Date: 2025-08-07 03:13:13.526998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71dfd553cd5b'
down_revision = 'd6709e14f414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyme_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pyme_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_pyme_pedido_pyme_id_user', 'user', ['pyme_id'], ['id'])
        batch_op.drop_column('rubro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyme_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubro', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_pyme_pedido_pyme_id_user', type_='foreignkey')
        batch_op.drop_column('pyme_id')

    # ### end Alembic commands ###
