"""inicial

Revision ID: 76b7b52a4428
Revises: 
Create Date: 2025-05-30 20:13:46.391804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '76b7b52a4428'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.String(length=500), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['padre_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sugerencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('nombre_empresa', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('link_web', sa.String(length=255), nullable=True),
    sa.Column('horario', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('preguntas_usadas', sa.Integer(), nullable=True),
    sa.Column('limite_preguntas', sa.Integer(), nullable=True),
    sa.Column('last_reset', sa.DateTime(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('catalogo_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.String(length=1024), nullable=True),
    sa.Column('precio', sa.String(length=50), nullable=True),
    sa.Column('embedding_vector', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogo_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=1024), nullable=True),
    sa.Column('precio', sa.String(length=50), nullable=True),
    sa.Column('cantidad', sa.String(length=50), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('embedding', sa.PickleType(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('fuente', sa.String(length=50), nullable=False),
    sa.Column('rubro', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversacion')
    op.drop_table('catalogo_item')
    op.drop_table('catalogo_embedding')
    op.drop_table('user')
    op.drop_table('sugerencia')
    op.drop_table('qa')
    op.drop_table('rubro')
    op.drop_table('logs')
    # ### end Alembic commands ###
