"""TicketComentario polimórfico

Revision ID: 7c5fd1990259
Revises: c9e37b9d69ae
Create Date: 2025-06-04 20:17:49.689011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5fd1990259'
down_revision = 'c9e37b9d69ae'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('_alembic_tmp_rubro')
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('rubro', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubro', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.drop_column('archivo_url')

    op.create_table('_alembic_tmp_rubro',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('clave', sa.VARCHAR(length=50), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('padre_id', sa.INTEGER(), nullable=True),
    sa.Column('s', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['padre_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.drop_table('pyme_ticket')
    op.drop_table('ticket_comentario')
    # ### end Alembic commands ###
