"""Hacer campos de PymePedido opcionales para migración

Revision ID: 8a36a966bd63
Revises: d724331bbed2
Create Date: 2025-06-12 05:28:54.882440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a36a966bd63'
down_revision = 'd724331bbed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalles', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.drop_column('detalles')

    # ### end Alembic commands ###
