"""Add units_per_pallet and suggested_price to CatalogoItem

Revision ID: 8e8cabaf31c8
Revises: 90d80cb381e4
Create Date: 2026-01-29 04:41:01.155303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8cabaf31c8'
down_revision = '90d80cb381e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogo_item', sa.Column('unidades_por_pallet', sa.Integer(), nullable=True))
    op.add_column('catalogo_item', sa.Column('precio_sugerido', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogo_item', 'precio_sugerido')
    op.drop_column('catalogo_item', 'unidades_por_pallet')
    # ### end Alembic commands ###
