"""add_categoria_id_to_pyme_ticket

Revision ID: 90d80cb381e4
Revises: 20300112_add_tenant_id_to_pyme_ticket
Create Date: 2026-01-06 14:41:21.924457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d80cb381e4'
down_revision = '20300112_add_tenant_id_to_pyme_ticket'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyme_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pyme_ticket_categoria_id', 'categorias_ticket', ['categoria_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyme_ticket', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pyme_ticket_categoria_id', type_='foreignkey')
        batch_op.drop_column('categoria_id')
    # ### end Alembic commands ###
