"""Agrega ciudad, provincia, lat, lng y horario_json a User

Revision ID: a03b1dd3e901
Revises: fb6a94c1c638
Create Date: 2025-05-30 14:05:05.439519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03b1dd3e901'
down_revision = 'fb6a94c1c638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('provincia', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pais', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('latitud', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitud', sa.Float(), nullable=True))
        batch_op.drop_column('ubicacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('longitud')
        batch_op.drop_column('latitud')
        batch_op.drop_column('pais')
        batch_op.drop_column('provincia')
        batch_op.drop_column('ciudad')

    # ### end Alembic commands ###
