"""Add archivo_adjunto_id to TicketComentario

Revision ID: a1b2c3d4e5f6
Revises: edb21c2c3bdd
Create Date: 2025-08-06 19:16:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'edb21c2c3bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_adjunto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_ticket_comentario_archivo_adjunto_id',
            'archivo_adjunto',
            ['archivo_adjunto_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_comentario', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ticket_comentario_archivo_adjunto_id', type_='foreignkey')
        batch_op.drop_column('archivo_adjunto_id')
    # ### end Alembic commands ###
