"""Update PymePedido model to allow anonymous users and include contact info

Revision ID: a2c074e6c0d1
Revises: 0ebfcfc75560
Create Date: 2025-06-10 02:13:44.106004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c074e6c0d1'
down_revision = '0ebfcfc75560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyme_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asunto', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('nombre_cliente', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_cliente', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefono_cliente', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rubro', sa.String(length=100), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyme_pedido', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('rubro')
        batch_op.drop_column('telefono_cliente')
        batch_op.drop_column('email_cliente')
        batch_op.drop_column('nombre_cliente')
        batch_op.drop_column('asunto')

    # ### end Alembic commands ###
