"""add_vecino_details_to_municipio_ticket

Revision ID: a77eb3e5e243
Revises: db48e3a4c174
Create Date: 2025-07-09 16:47:50.226011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77eb3e5e243'
down_revision = 'db48e3a4c174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_municipio_ticket')
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_vecino', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('telefono_vecino', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('email_vecino', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('foto_url_directa', sa.String(length=255), nullable=True))
        batch_op.drop_column('archivo_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivo_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('foto_url_directa')
        batch_op.drop_column('email_vecino')
        batch_op.drop_column('telefono_vecino')
        batch_op.drop_column('nombre_vecino')

    op.create_table('_alembic_tmp_municipio_ticket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pregunta', sa.TEXT(), nullable=False),
    sa.Column('asunto', sa.VARCHAR(length=200), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=30), nullable=True),
    sa.Column('anon_id', sa.VARCHAR(length=80), nullable=True),
    sa.Column('ultima_actividad', sa.DATETIME(), nullable=True),
    sa.Column('nro_ticket', sa.INTEGER(), nullable=False),
    sa.Column('detalles', sa.TEXT(), nullable=True),
    sa.Column('direccion', sa.VARCHAR(length=255), nullable=True),
    sa.Column('latitud', sa.FLOAT(), nullable=True),
    sa.Column('longitud', sa.FLOAT(), nullable=True),
    sa.Column('fecha', sa.DATETIME(), nullable=True),
    sa.Column('municipio_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_ticket')
    )
    # ### end Alembic commands ###
