"""add fecha_creacion to user

Revision ID: a9ffe38fb399
Revises: ac249b67a8f9
Create Date: 2025-06-30 09:13:02.340048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ffe38fb399'
down_revision = 'ac249b67a8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente_nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_user_id', sa.Integer(), nullable=False),
    sa.Column('creada_por_user_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['creada_por_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente_nota', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_nota_cliente_user_id'), ['cliente_user_id'], unique=False)

    op.create_table('sugerencia_ciudadano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anon_id', sa.String(length=80), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('texto_sugerencia', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sugerencia_ciudadano', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sugerencia_ciudadano_anon_id'), ['anon_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion')

    with op.batch_alter_table('sugerencia_ciudadano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sugerencia_ciudadano_anon_id'))

    op.drop_table('sugerencia_ciudadano')
    with op.batch_alter_table('cliente_nota', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_nota_cliente_user_id'))

    op.drop_table('cliente_nota')
    # ### end Alembic commands ###
