"""add_desc_corta_promocion_to_catalogoitem

Revision ID: abcdef123456
Revises: ee3694e2e48a
Create Date: 2023-11-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcdef123456'
down_revision = 'ee3694e2e48a' # La última revisión conocida
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion_corta', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('promocion_info', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_item', schema=None) as batch_op:
        batch_op.drop_column('promocion_info')
        batch_op.drop_column('descripcion_corta')

    # ### end Alembic commands ###
