"""Add plantillas_respuesta table

Revision ID: b1d4f3e7a2c1
Revises: ee3694e2e48a
Create Date: 2024-07-25 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d4f3e7a2c1'
down_revision = 'ee3694e2e48a' # Asumiendo que esta es la cabeza anterior
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plantillas_respuesta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.current_timestamp()),
    sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.current_timestamp(), onupdate=sa.func.current_timestamp()),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plantillas_respuesta')
    # ### end Alembic commands ###
