"""Add multimodal ticket and PR-06 PR-07 models

Revision ID: b1efa5b6dd9a
Revises: a6dfab11f261
Create Date: 2026-04-23 17:36:57.775446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1efa5b6dd9a'
down_revision = 'a6dfab11f261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
