"""municipio tickets

Revision ID: c9e37b9d69ae
Revises: 3550466abf47
Create Date: 2025-06-04 13:27:48.363498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e37b9d69ae'
down_revision = '3550466abf47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('municipio_ticket',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('pregunta', sa.Text(), nullable=False),
    #     sa.Column('user_id', sa.Integer(), nullable=True),
    #     sa.Column('estado', sa.String(length=30), nullable=True),
    #     sa.Column('nro_ticket', sa.Integer(), nullable=False),
    #     sa.Column('fecha', sa.DateTime(), nullable=True),
    #     sa.PrimaryKeyConstraint('id'),
    #     sa.UniqueConstraint('nro_ticket')
    # )
    # with op.batch_alter_table('rubro', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('s', sa.String(length=100), nullable=False))
    #     batch_op.drop_column('nombre')

    pass  # <- importante, no borres esto

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rubro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('s')

    op.drop_table('municipio_ticket')
    # ### end Alembic commands ###
