"""empty message

Revision ID: cd15c60c3b97
Revises: 78ec2d442718
Create Date: 2025-07-23 00:29:40.505487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'cd15c60c3b97'
down_revision = '78ec2d442718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.String(length=500), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantillas_respuesta',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.PickleType(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('padre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['padre_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('ticket_satisfaccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pyme_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('anon_id', sa.String(length=80), nullable=True),
    sa.Column('nro_ticket', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('archivo_url', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('estado_cliente', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_ticket')
    )
    with op.batch_alter_table('pyme_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pyme_ticket_anon_id'), ['anon_id'], unique=False)

    op.create_table('qa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sugerencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('rol', sa.String(length=30), nullable=True),
    sa.Column('tipo_chat', sa.String(length=20), nullable=True),
    sa.Column('pyme_id', sa.Integer(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('nombre_empresa', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('link_web', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('color_primario', sa.String(length=20), nullable=True),
    sa.Column('color_secundario', sa.String(length=20), nullable=True),
    sa.Column('badge_tipo', sa.String(length=20), nullable=True),
    sa.Column('acepto_terminos', sa.Boolean(), nullable=True),
    sa.Column('fecha_aceptacion_terminos', sa.DateTime(), nullable=True),
    sa.Column('acepta_marketing', sa.Boolean(), nullable=True),
    sa.Column('fecha_aceptacion_marketing', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('ticket_categorias', sa.String(length=255), nullable=True),
    sa.Column('horario', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('preguntas_usadas', sa.Integer(), nullable=True),
    sa.Column('limite_preguntas', sa.Integer(), nullable=True),
    sa.Column('last_reset', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('catalogo_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.String(length=1024), nullable=True),
    sa.Column('precio', sa.String(length=50), nullable=True),
    sa.Column('embedding_vector', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogo_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=1024), nullable=True),
    sa.Column('precio', sa.String(length=50), nullable=True),
    sa.Column('cantidad', sa.String(length=50), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('descripcion_corta', sa.String(length=512), nullable=True),
    sa.Column('promocion_info', sa.String(length=255), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('embedding', sa.PickleType(), nullable=True),
    sa.Column('imagen_url', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogo_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogo_item_marca'), ['marca'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalogo_item_sku'), ['sku'], unique=False)

    op.create_table('chat_session_context',
    sa.Column('chat_session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anon_id', sa.String(length=80), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('chat_session_id')
    )
    with op.batch_alter_table('chat_session_context', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_session_context_anon_id'), ['anon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_session_context_user_id'), ['user_id'], unique=False)

    op.create_table('cliente_nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_user_id', sa.Integer(), nullable=False),
    sa.Column('creada_por_user_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['creada_por_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente_nota', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_nota_cliente_user_id'), ['cliente_user_id'], unique=False)

    op.create_table('conversacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=False),
    sa.Column('fuente', sa.String(length=50), nullable=False),
    sa.Column('rubro', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversacion', schema=None) as batch_op:
        batch_op.create_index('ix_conversacion_session_id', ['session_id'], unique=False)

    op.create_table('municipio_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('anon_id', sa.String(length=80), nullable=True),
    sa.Column('ultima_actividad', sa.DateTime(), nullable=True),
    sa.Column('nro_ticket', sa.String(length=36), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('nombre_vecino', sa.String(length=150), nullable=True),
    sa.Column('telefono_vecino', sa.String(length=30), nullable=True),
    sa.Column('email_vecino', sa.String(length=120), nullable=True),
    sa.Column('foto_url_directa', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['municipio_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_ticket')
    )
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_municipio_ticket_anon_id'), ['anon_id'], unique=False)

    op.create_table('promocion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pyme_user_id', sa.Integer(), nullable=False),
    sa.Column('nombre_promocion', sa.String(length=255), nullable=False),
    sa.Column('descripcion_publica', sa.Text(), nullable=True),
    sa.Column('tipo_promocion', sa.String(length=100), nullable=False),
    sa.Column('valor_descuento', sa.Float(), nullable=True),
    sa.Column('cantidad_condicion_x', sa.Integer(), nullable=True),
    sa.Column('cantidad_resultado_y', sa.Integer(), nullable=True),
    sa.Column('cantidad_minima_aplicable', sa.Integer(), nullable=True),
    sa.Column('monto_minimo_carrito', sa.Float(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('codigo_promocion', sa.String(length=50), nullable=True),
    sa.Column('uso_maximo_general', sa.Integer(), nullable=True),
    sa.Column('usos_actuales_general', sa.Integer(), nullable=True),
    sa.Column('uso_maximo_por_cliente', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pyme_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promocion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promocion_codigo_promocion'), ['codigo_promocion'], unique=True)
        batch_op.create_index(batch_op.f('ix_promocion_pyme_user_id'), ['pyme_user_id'], unique=False)

    op.create_table('pyme_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nro_pedido', sa.String(length=50), nullable=False),
    sa.Column('asunto', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('monto_total', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('nombre_cliente', sa.String(length=100), nullable=True),
    sa.Column('email_cliente', sa.String(length=100), nullable=True),
    sa.Column('telefono_cliente', sa.String(length=50), nullable=True),
    sa.Column('rubro', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nro_pedido')
    )
    op.create_table('recordatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=False),
    sa.Column('enviado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sitio_web_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rubro_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('datos_json', sa.Text(), nullable=False),
    sa.Column('fecha_scraping', sa.DateTime(), nullable=True),
    sa.Column('actualizado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sugerencia_ciudadano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anon_id', sa.String(length=80), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('texto_sugerencia', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sugerencia_ciudadano', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sugerencia_ciudadano_anon_id'), ['anon_id'], unique=False)

    op.create_table('whatsapp_numero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_whatsapp', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_numero', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_numero_numero_whatsapp'), ['numero_whatsapp'], unique=True)

    op.create_table('archivo_adjunto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('tamano', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('pyme_ticket_id', sa.Integer(), nullable=True),
    sa.Column('municipio_ticket_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_ticket_id'], ['municipio_ticket.id'], ),
    sa.ForeignKeyConstraint(['pyme_ticket_id'], ['pyme_ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promocion_alcance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('promocion_id', sa.String(length=36), nullable=False),
    sa.Column('tipo_alcance', sa.String(length=50), nullable=False),
    sa.Column('catalogo_item_id', sa.Integer(), nullable=True),
    sa.Column('nombre_categoria', sa.String(length=100), nullable=True),
    sa.Column('nombre_marca', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['catalogo_item_id'], ['catalogo_item.id'], ),
    sa.ForeignKeyConstraint(['promocion_id'], ['promocion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('promocion_alcance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_promocion_alcance_catalogo_item_id'), ['catalogo_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_promocion_alcance_nombre_categoria'), ['nombre_categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_promocion_alcance_nombre_marca'), ['nombre_marca'], unique=False)
        batch_op.create_index(batch_op.f('ix_promocion_alcance_promocion_id'), ['promocion_id'], unique=False)

    op.create_table('reaccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversacion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('emoji', sa.String(length=5), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversacion_id'], ['conversacion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pyme_ticket_id', sa.Integer(), nullable=True),
    sa.Column('municipio_ticket_id', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anon_id', sa.String(length=80), nullable=True),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_ticket_id'], ['municipio_ticket.id'], ),
    sa.ForeignKeyConstraint(['pyme_ticket_id'], ['pyme_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_comentario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_comentario_anon_id'), ['anon_id'], unique=False)

    op.create_table('analisis_archivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archivo_adjunto_id', sa.Integer(), nullable=False),
    sa.Column('resumen', sa.Text(), nullable=True),
    sa.Column('estado_analisis', sa.String(length=50), nullable=True),
    sa.Column('fecha_analisis', sa.DateTime(), nullable=True),
    sa.Column('error_analisis', sa.Text(), nullable=True),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('datos_estructurados', sa.JSON(), nullable=True),
    sa.Column('tipo_analisis', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['archivo_adjunto_id'], ['archivo_adjunto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analisis_archivo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analisis_archivo_archivo_adjunto_id'), ['archivo_adjunto_id'], unique=False)

    op.create_table('catalogo_compartido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalogo_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_id', sa.Integer(), nullable=False),
    sa.Column('fecha_compartido', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['catalogo_id'], ['archivo_adjunto.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shared_with_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalogo_compartido')
    with op.batch_alter_table('analisis_archivo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analisis_archivo_archivo_adjunto_id'))

    op.drop_table('analisis_archivo')
    with op.batch_alter_table('ticket_comentario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_comentario_anon_id'))

    op.drop_table('ticket_comentario')
    op.drop_table('reaccion')
    with op.batch_alter_table('promocion_alcance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promocion_alcance_promocion_id'))
        batch_op.drop_index(batch_op.f('ix_promocion_alcance_nombre_marca'))
        batch_op.drop_index(batch_op.f('ix_promocion_alcance_nombre_categoria'))
        batch_op.drop_index(batch_op.f('ix_promocion_alcance_catalogo_item_id'))

    op.drop_table('promocion_alcance')
    op.drop_table('archivo_adjunto')
    with op.batch_alter_table('whatsapp_numero', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_numero_numero_whatsapp'))

    op.drop_table('whatsapp_numero')
    with op.batch_alter_table('sugerencia_ciudadano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sugerencia_ciudadano_anon_id'))

    op.drop_table('sugerencia_ciudadano')
    op.drop_table('sitio_web_info')
    op.drop_table('recordatorio')
    op.drop_table('pyme_pedido')
    with op.batch_alter_table('promocion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_promocion_pyme_user_id'))
        batch_op.drop_index(batch_op.f('ix_promocion_codigo_promocion'))

    op.drop_table('promocion')
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_municipio_ticket_anon_id'))

    op.drop_table('municipio_ticket')
    with op.batch_alter_table('conversacion', schema=None) as batch_op:
        batch_op.drop_index('ix_conversacion_session_id')

    op.drop_table('conversacion')
    with op.batch_alter_table('cliente_nota', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_nota_cliente_user_id'))

    op.drop_table('cliente_nota')
    with op.batch_alter_table('chat_session_context', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_session_context_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_session_context_anon_id'))

    op.drop_table('chat_session_context')
    with op.batch_alter_table('catalogo_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogo_item_sku'))
        batch_op.drop_index(batch_op.f('ix_catalogo_item_marca'))

    op.drop_table('catalogo_item')
    op.drop_table('catalogo_embedding')
    op.drop_table('user')
    op.drop_table('sugerencia')
    op.drop_table('qa')
    with op.batch_alter_table('pyme_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pyme_ticket_anon_id'))

    op.drop_table('pyme_ticket')
    op.drop_table('ticket_satisfaccion')
    op.drop_table('rubro')
    op.drop_table('plantillas_respuesta')
    op.drop_table('logs')
    # ### end Alembic commands ###
