"""Add LlmInteractionLog table

Revision ID: ce8254522e14
Revises: 071dc98a431a
Create Date: 2025-08-19 21:46:06.065601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8254522e14'
down_revision = '071dc98a431a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_interaction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_session_id', sa.String(length=36), nullable=False),
    sa.Column('user_query', sa.Text(), nullable=False),
    sa.Column('llm_response_raw', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_session_context.chat_session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_interaction_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_interaction_log_chat_session_id'), ['chat_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_interaction_log_status'), ['status'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('prefers_audio',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('prefers_audio',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('llm_interaction_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_interaction_log_status'))
        batch_op.drop_index(batch_op.f('ix_llm_interaction_log_chat_session_id'))

    op.drop_table('llm_interaction_log')
    # ### end Alembic commands ###
