"""Add prefers_audio to User model

Revision ID: d31a13125cc3
Revises: 040692e9390e
Create Date: 2025-08-13 00:22:12.829386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31a13125cc3'
down_revision = '040692e9390e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefers_audio', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('prefers_audio')

    # ### end Alembic commands ###
