"""Hacer campos de PymePedido opcionales para migración

Revision ID: d724331bbed2
Revises: 5f78969571e8
Create Date: 2025-06-11 09:24:08.259894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd724331bbed2'
down_revision = '5f78969571e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_actividad', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.drop_column('ultima_actividad')

    # ### end Alembic commands ###
