"""add sku and marca to catalogo_item

Revision ID: e1b12ba1d6c6
Revises: 2986dd81b914
Create Date: 2025-06-02 20:03:19.356792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b12ba1d6c6'
down_revision = '2986dd81b914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('marca', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_catalogo_item_marca'), ['marca'], unique=False)
        batch_op.create_index(batch_op.f('ix_catalogo_item_sku'), ['sku'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogo_item_sku'))
        batch_op.drop_index(batch_op.f('ix_catalogo_item_marca'))
        batch_op.drop_column('marca')
        batch_op.drop_column('sku')

    # ### end Alembic commands ###
