"""mensaje corto

Revision ID: e912a663dd9e
Revises: 60e14df94985
Create Date: 2025-07-30 00:30:34.894470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e912a663dd9e'
down_revision = '60e14df94985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantillas_respuesta', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=sa.BLOB(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plantillas_respuesta', schema=None) as batch_op:
        batch_op.alter_column('embedding',
               existing_type=sa.JSON(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
