"""add imagen_url to catalogo_item

Revision ID: e9d7c7b7d8a5
Revises: c9c5e5bfdafb
Create Date: 2025-07-17 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d7c7b7d8a5'
down_revision = 'c9c5e5bfdafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_item', schema=None) as batch_op:
        batch_op.drop_column('imagen_url')

    # ### end Alembic commands ###
