"""Agrego session_id a tabla Conversacion

Revision ID: f8d892575a95
Revises: a01be9e5904b
Create Date: 2025-06-06 20:00:32.053606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d892575a95'
down_revision = 'a01be9e5904b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asunto', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=True))

    with op.batch_alter_table('pyme_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asunto', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pyme_ticket', schema=None) as batch_op:
        batch_op.drop_column('categoria')
        batch_op.drop_column('asunto')

    with op.batch_alter_table('municipio_ticket', schema=None) as batch_op:
        batch_op.drop_column('categoria')
        batch_op.drop_column('asunto')

    # ### end Alembic commands ###
