"""Pending schema: activate only in a coordinated CRM task rollout.
No existing contact data or follow-up fields are migrated.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '20260924_crm_tasks_v1'
down_revision = '20260820_survey_content_jurisdiction_v1'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("priority IN ('normal','high','urgent')", name='ck_crm_task_priority'),
    sa.CheckConstraint("status IN ('todo','in_progress','done','cancelled')", name='ck_crm_task_status'),
    sa.CheckConstraint('revision > 0', name='ck_crm_task_revision'),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_profile.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_crm_task_tenant_id')
    )
    op.create_index('ix_crm_task_assignment_due', 'crm_task', ['tenant_id', 'assignee_id', 'status', 'due_at'], unique=False)
    op.create_index('ix_crm_task_contact_created', 'crm_task', ['tenant_id', 'contact_id', 'created_at', 'id'], unique=False)
    op.create_table('crm_task_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('task_revision', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=1200), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('before_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("operation IN ('created','updated')", name='ck_crm_task_event_operation'),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'task_id'], ['crm_task.tenant_id', 'crm_task.id'], name='fk_crm_task_event_task'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'actor_id', 'key_hash', name='uq_crm_task_event_request'),
    sa.UniqueConstraint('tenant_id', 'task_id', 'task_revision', name='uq_crm_task_event_revision')
    )
    op.create_index('ix_crm_task_event_history', 'crm_task_event', ['tenant_id', 'task_id', 'task_revision'], unique=False)
    _install_guards()


def _install_guards():
    dialect = op.get_bind().dialect.name
    if dialect == 'sqlite':
        for operation in ('UPDATE','DELETE'):
            op.execute(f"CREATE TRIGGER crm_task_event_no_{operation.lower()} BEFORE {operation} ON crm_task_event BEGIN SELECT RAISE(ABORT, 'crm_task_event_append_only'); END")
        for operation in ('INSERT','UPDATE'):
            op.execute(f"CREATE TRIGGER crm_task_contact_scope_{operation.lower()} BEFORE {operation} ON crm_task WHEN NOT EXISTS (SELECT 1 FROM contact WHERE id=NEW.contact_id AND tenant_id=NEW.tenant_id) BEGIN SELECT RAISE(ABORT, 'crm_task_contact_scope'); END")
    elif dialect == 'postgresql':
        op.execute("""CREATE FUNCTION crm_task_event_immutable() RETURNS trigger AS $$
            BEGIN RAISE EXCEPTION 'crm_task_event_append_only'; END;
            $$ LANGUAGE plpgsql""")
        op.execute("CREATE TRIGGER crm_task_event_immutable BEFORE UPDATE OR DELETE ON crm_task_event FOR EACH ROW EXECUTE FUNCTION crm_task_event_immutable()")
        op.execute("""CREATE FUNCTION crm_task_contact_scope() RETURNS trigger AS $$
            BEGIN IF NOT EXISTS (SELECT 1 FROM contact WHERE id=NEW.contact_id AND tenant_id=NEW.tenant_id)
              THEN RAISE EXCEPTION 'crm_task_contact_scope'; END IF; RETURN NEW; END;
            $$ LANGUAGE plpgsql""")
        op.execute("CREATE TRIGGER crm_task_contact_scope BEFORE INSERT OR UPDATE ON crm_task FOR EACH ROW EXECUTE FUNCTION crm_task_contact_scope()")
    else:
        raise RuntimeError('CRM tasks require PostgreSQL or SQLite')


def downgrade():
    raise RuntimeError('CRM task history requires an explicit reviewed retention plan; automatic downgrade is disabled')
